
//! CLI command stubs — generated from ontology/cli-open-ontologies.ttl
//!
//! Generated by ggen. Do not edit — regenerate with: ggen sync
//!
//! Architecture:
//!   Tier 1  — ontology/cli-open-ontologies.ttl   (source of truth)
//!   Tier 2  — ggen sync                          (manufacturing step)
//!   Tier 3  — src/cmds/generated.rs              (this file, wired to lib)
//!
//! Each module corresponds to a top-level CLI noun (command).
//! Verb implementations live in src/cmds/<noun>.rs (hand-written).

// ============================================================================
// DOCTOR — Health diagnostics

// ============================================================================
/// Check the health of the open-ontologies installation and data directory.
///
/// Generated stub — wired to src/cmds/doctor.rs
#[allow(dead_code)]
pub mod doctor_stub {
    use clap_noun_verb::NounVerbError;
    use clap_noun_verb::Result as NounVerbResult;

    /// Not yet wired — 9 subcommand(s) defined in ontology.
    /// Real implementation: src/cmds/doctor.rs
    pub fn not_yet_wired() -> NounVerbResult<serde_json::Value> {
        Err(NounVerbError::execution_error("not yet wired"))
    }
}

// ============================================================================
// MARKETPLACE — Ontology marketplace

// ============================================================================
/// Browse and install standard ontologies from the curated catalogue.
///
/// Generated stub — wired to src/cmds/marketplace.rs
#[allow(dead_code)]
pub mod marketplace_stub {
    use clap_noun_verb::NounVerbError;
    use clap_noun_verb::Result as NounVerbResult;

    /// Not yet wired — 2 subcommand(s) defined in ontology.
    /// Real implementation: src/cmds/marketplace.rs
    pub fn not_yet_wired() -> NounVerbResult<serde_json::Value> {
        Err(NounVerbError::execution_error("not yet wired"))
    }
}

// ============================================================================
// CLINICAL — Clinical terminology operations

// ============================================================================
/// Crosswalk, enrich, and validate clinical ontologies against ICD-10/SNOMED/MeSH.
///
/// Generated stub — wired to src/cmds/clinical.rs
#[allow(dead_code)]
pub mod clinical_stub {
    use clap_noun_verb::NounVerbError;
    use clap_noun_verb::Result as NounVerbResult;

    /// Not yet wired — 3 subcommand(s) defined in ontology.
    /// Real implementation: src/cmds/clinical.rs
    pub fn not_yet_wired() -> NounVerbResult<serde_json::Value> {
        Err(NounVerbError::execution_error("not yet wired"))
    }
}

// ============================================================================
// ALIGNMENT — Ontology alignment and feedback

// ============================================================================
/// Align ontologies, provide feedback on alignment candidates, lint rules, and enforce rules.
///
/// Generated stub — wired to src/cmds/alignment.rs
#[allow(dead_code)]
pub mod alignment_stub {
    use clap_noun_verb::NounVerbError;
    use clap_noun_verb::Result as NounVerbResult;

    /// Not yet wired — 4 subcommand(s) defined in ontology.
    /// Real implementation: src/cmds/alignment.rs
    pub fn not_yet_wired() -> NounVerbResult<serde_json::Value> {
        Err(NounVerbError::execution_error("not yet wired"))
    }
}

// ============================================================================
// GOVERNANCE — Ontology lifecycle governance

// ============================================================================
/// Plan, apply, lock, enforce, monitor, and track lineage for ontology changes.
///
/// Generated stub — wired to src/cmds/governance.rs
#[allow(dead_code)]
pub mod governance_stub {
    use clap_noun_verb::NounVerbError;
    use clap_noun_verb::Result as NounVerbResult;

    /// Not yet wired — 9 subcommand(s) defined in ontology.
    /// Real implementation: src/cmds/governance.rs
    pub fn not_yet_wired() -> NounVerbResult<serde_json::Value> {
        Err(NounVerbError::execution_error("not yet wired"))
    }
}

// ============================================================================
// DATA — Data ingestion and integration

// ============================================================================
/// Ingest structured data, map to ontology classes, pull/push from SPARQL endpoints, import OWL and schemas.
///
/// Generated stub — wired to src/cmds/data.rs
#[allow(dead_code)]
pub mod data_stub {
    use clap_noun_verb::NounVerbError;
    use clap_noun_verb::Result as NounVerbResult;

    /// Not yet wired — 9 subcommand(s) defined in ontology.
    /// Real implementation: src/cmds/data.rs
    pub fn not_yet_wired() -> NounVerbResult<serde_json::Value> {
        Err(NounVerbError::execution_error("not yet wired"))
    }
}

// ============================================================================
// SERVER — Server lifecycle management

// ============================================================================
/// Serve the ontology engine over MCP stdio, HTTP, or Unix socket; initialize the data directory.
///
/// Generated stub — wired to src/cmds/server.rs
#[allow(dead_code)]
pub mod server_stub {
    use clap_noun_verb::NounVerbError;
    use clap_noun_verb::Result as NounVerbResult;

    /// Not yet wired — 4 subcommand(s) defined in ontology.
    /// Real implementation: src/cmds/server.rs
    pub fn not_yet_wired() -> NounVerbResult<serde_json::Value> {
        Err(NounVerbError::execution_error("not yet wired"))
    }
}

// ============================================================================
// ONTOLOGY — Core RDF/OWL operations

// ============================================================================
/// Load, save, validate, query, lint, convert, diff, version, and reason over ontologies.
///
/// Generated stub — wired to src/cmds/ontology.rs
#[allow(dead_code)]
pub mod ontology_stub {
    use clap_noun_verb::NounVerbError;
    use clap_noun_verb::Result as NounVerbResult;

    /// Not yet wired — 15 subcommand(s) defined in ontology.
    /// Real implementation: src/cmds/ontology.rs
    pub fn not_yet_wired() -> NounVerbResult<serde_json::Value> {
        Err(NounVerbError::execution_error("not yet wired"))
    }
}
