
// ============================================================
// DO NOT EDIT THIS FILE
//
// This file is auto-generated by ggen from:
//   ontology/revops-manufacturing.ttl
//
// Regenerate with: ggen sync
// The product is CodeManufactory; RevOps is merely proof that
// CodeManufactory works.
// ============================================================

//! RevOps manufacturing stage constants — generated from ontology/revops-manufacturing.ttl
//!
//! Stages are ordered by `revops:stageOrder` (ascending).
//! Each stage name corresponds to an OCEL event type emitted during manufacturing.

/// Ordered manufacturing stage names for the CodeManufactory RevOps test case.
///
/// These correspond to `revops:stageName` values in `ontology/revops-manufacturing.ttl`.
/// The sequence maps directly to OCEL event types; Cell8 gate A13 verifies that
/// every artifact traverses all stages in this exact order.
pub const REVOPS_STAGES: &[&str] = &[
    "certify",
    "manufacture",
    "qualify",
    "seed",
];

/// Number of manufacturing stages in the RevOps profile.
#[allow(dead_code)]
pub const REVOPS_STAGE_COUNT: usize = REVOPS_STAGES.len();
