
// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/notifications.ttl + extract-push-card-fields.rq

import { PushCard } from '../types/notifications';







export const PUSH_CARDS: PushCard[] = [

  {
    title: "Volunteer Request Card",
    subtitle: "Ministry Services",
    body: "You have been requested to serve as a volunteer for an upcoming ministry route stage. Please accept or decline.",
    action: "Respond Now",
    deepLink: "zoela://volunteer/request",
    priority: 2,
  },

];
