
-- =============================================================================
-- ZOE LA Supabase Migration — generated from admissibility-gated extraction
-- =============================================================================
-- DO NOT EDIT. Generated by ggen from:
--   ontology/zoela/*.ttl                                    (church-service domain)
--   ontology/profiles/zoela-supabase-materialization.ttl    (kinds + priorities)
--   ontology/profiles/public-role-shapes.ttl                (SHACL contracts)
--   ontology/profiles/zoela-supabase-rls.ttl                (ODRL → RLS mapping)
-- Regenerate with: ggen sync --rule zoela-public-materialization
--
-- Doctrine: a table appears here only when ALL four admission conditions hold —
-- public-anchor specialization, SHACL shape, ODRL policy (if rlsRequired), and
-- ggen:emitsSql=true on the materialization kind with no priority ambiguity.
-- Refusals are audited in supabase-materialization-refusals.tera, not here.
-- See: memory/feedback_public_vocab_materialization.md
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- ----------------------------------------------------------------------------
-- Admitted materializations: 5
-- (Every row below is admitted by construction. Refusals → supabase-materialization-refusals.sql)
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- Push Notification (ActionMaterialization)
--   Local class:          https://zoela.org/ontology/PushNotification
--   Public anchor:        https://schema.org/Action
--   Materialization kind: https://open-ontologies.org/ggen#ActionMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#ActionMaterializationShape
--   A push notification dispatched to a PersonProfile's device when a RouteStage transition occurs. Carries a title, body, category, and deep-link route back into the app.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS push_notification (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  -- Full body text of the push notification providing context and call-to-action.
  notification_body TEXT,
  -- Short headline text of the push notification  displayed in the device notification shade.
  notification_title TEXT,
  -- Links a PushNotification to the RouteStage whose completion or activation triggered the notification dispatch.
  triggered_by_stage UUID,
  -- Expo deep-link URI that opens the relevant screen in ZOE LA Mobile when the notification is tapped.
  deep_link_route TEXT,
  -- Category identifier from the NotificationCategoryScheme  used to route and filter notifications in the app.
  notification_category TEXT,
  -- Links a PushNotification to the PersonProfile whose device receives the notification.
  sent_to_person UUID,
  created_by  UUID NOT NULL REFERENCES auth.users(id)
);

ALTER TABLE push_notification ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER set_push_notification_updated_at
  BEFORE UPDATE ON push_notification
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- ----------------------------------------------------------------------------
-- Partner Capacity (EvidenceEntityMaterialization)
--   Local class:          https://zoela.org/ontology/PartnerCapacity
--   Public anchor:        http://www.w3.org/ns/prov#Entity
--   Materialization kind: https://open-ontologies.org/ggen#EvidenceEntityMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#EvidenceEntityMaterializationShape
--   Service capacity offered by an external partner organization that can fulfill relayed needs.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS part_cap (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  -- The type of resource or service this capacity record describes  e.g. food  clothing  counseling  housing.
  resourcetype TEXT,
  -- The identifier of the partner organization to which this capacity record belongs.
  capacitypartnerid TEXT,
  -- The date and time when the current availability count was last updated.
  availabilityupdatedat TIMESTAMPTZ,
  -- The number of individuals or households currently on the waitlist for this resource type at the partner organization.
  waitlistcount INTEGER,
  -- The total weekly service capacity of the partner organization for this resource type.
  weeklycapacity INTEGER,
  -- The number of service slots currently available at the partner organization for this resource type.
  currentavailability INTEGER
);

ALTER TABLE part_cap ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER set_part_cap_updated_at
  BEFORE UPDATE ON part_cap
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- ----------------------------------------------------------------------------
-- Resource Need Match (EvidenceActivityMaterialization)
--   Local class:          https://zoela.org/ontology/ResourceNeedMatch
--   Public anchor:        http://www.w3.org/ns/prov#Activity
--   Materialization kind: https://open-ontologies.org/ggen#EvidenceActivityMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#EvidenceActivityMaterializationShape
--   A bridge object recording a lawful many-to-many relationship between a service need and a matching resource allocation. Carries match quantity, status, and routing metadata.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS resource_need_match (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  -- ISO-8601 timestamp when this need-resource match was created.
  matched_at TIMESTAMPTZ,
  -- Current lifecycle state of this match from a SKOS controlled vocabulary.
  match_status UUID,
  -- When true  the routing engine may fulfill this match with a resource from an equivalent substitute category.
  substitute_allowed BOOLEAN,
  -- Quantity of the resource (in resource units) allocated to this need match.
  quantity_matched NUMERIC,
  -- When true  fulfillment of this match may be relayed to an external partner organization's capacity.
  partner_relay_allowed BOOLEAN,
  -- Identifier of the service need being matched. Foreign key to the need domain.
  need_id TEXT,
  -- UUID primary key uniquely identifying this need-resource match record.
  match_id TEXT,
  -- Code of the resource type allocated to satisfy this need. Foreign key to zoe Resource.
  resource_code TEXT
);

ALTER TABLE resource_need_match ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER set_resource_need_match_updated_at
  BEFORE UPDATE ON resource_need_match
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- ----------------------------------------------------------------------------
-- Group Meeting (EventMaterialization)
--   Local class:          https://zoela.org/ontology/GroupMeeting
--   Public anchor:        https://schema.org/Event
--   Materialization kind: https://open-ontologies.org/ggen#EventMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#EventMaterializationShape
--   An individual meeting instance of a Connect Group, derived from the GroupSchedule. Records the actual meeting date, start time, physical location, and cancellation status.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS group_meeting (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  -- ISO-8601 time-of-day at which this specific meeting instance begins.
  meeting_start_time TEXT,
  -- Associates the GroupMeeting with its Connect Group.
  meeting_for_group UUID,
  -- True when this specific meeting instance has been cancelled. Cancelled meetings are retained in the event log for process-mining completeness.
  meeting_is_cancelled BOOLEAN,
  -- Links the meeting instance back to the GroupSchedule from which it was generated.
  meeting_derived_from_schedule UUID REFERENCES group_schedule(id),
  -- ISO-8601 calendar date of the individual meeting instance.
  meeting_date DATE,
  -- Human-readable address or platform description for this meeting instance  e.g. '123 Main St  Room 4' or 'Zoom link in group chat'.
  meeting_location TEXT
);

ALTER TABLE group_meeting ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER set_group_meeting_updated_at
  BEFORE UPDATE ON group_meeting
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- ----------------------------------------------------------------------------
-- Prayer Request (ActionMaterialization)
--   Local class:          https://zoela.org/ontology/PrayerRequest
--   Public anchor:        https://schema.org/RequestAction
--   Materialization kind: https://open-ontologies.org/ggen#ActionMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#ActionMaterializationShape
--   Requests for intercessory prayer, which may also indicate underlying pastoral need.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS prayer_request (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  -- Number of members who have indicated they are interceding for this prayer request.
  prayed_for_count INTEGER,
  -- True if the event is visible to unregistered visitors; false if restricted to members.
  is_public BOOLEAN,
  -- Identifier of the ZOE LA campus to which this prayer request is routed for pastoral follow-up.
  campus_id TEXT,
  created_by  UUID NOT NULL REFERENCES auth.users(id)
);

ALTER TABLE prayer_request ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER set_prayer_request_updated_at
  BEFORE UPDATE ON prayer_request
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- =============================================================================
-- End of generated migration. Every table above passed all admissibility gates.
-- Refused candidates appear in supabase-materialization-refusals.sql, not here.
-- =============================================================================
