
-- =============================================================================
-- ZOE LA Supabase Migration — generated from admissibility-gated extraction
-- =============================================================================
-- DO NOT EDIT. Generated by ggen from:
--   ontology/zoela/*.ttl                                    (church-service domain)
--   ontology/profiles/zoela-supabase-materialization.ttl    (kinds + priorities)
--   ontology/profiles/public-role-shapes.ttl                (SHACL contracts)
--   ontology/profiles/zoela-supabase-rls.ttl                (ODRL → RLS mapping)
-- Regenerate with: ggen sync --rule zoela-public-materialization
--
-- Doctrine: a table appears here only when ALL four admission conditions hold —
-- public-anchor specialization, SHACL shape, ODRL policy (if rlsRequired), and
-- ggen:emitsSql=true on the materialization kind with no priority ambiguity.
-- Refusals are audited in supabase-materialization-refusals.tera, not here.
-- See: memory/feedback_public_vocab_materialization.md
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;
-- ----------------------------------------------------------------------------
-- Admitted materializations: 1
-- (Every row below is admitted by construction. Refusals → supabase-materialization-refusals.sql)
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- Push Notification (ActionMaterialization)
--   Local class:          https://zoela.org/ontology/PushNotification
--   Public anchor:        https://schema.org/Action
--   Materialization kind: https://open-ontologies.org/ggen#ActionMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#ActionMaterializationShape
--   A push notification dispatched to a PersonProfile's device when a RouteStage transition occurs. Carries a title, body, category, and deep-link route back into the app.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS push_notification (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  created_by  UUID NOT NULL REFERENCES auth.users(id)
);

ALTER TABLE push_notification ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER set_push_notification_updated_at
  BEFORE UPDATE ON push_notification
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- =============================================================================
-- End of generated migration. Every table above passed all admissibility gates.
-- Refused candidates appear in supabase-materialization-refusals.sql, not here.
-- =============================================================================
