
-- =============================================================================
-- ZOE LA Supabase RLS — generated from ODRL policy chain
-- =============================================================================
-- DO NOT EDIT. Generated by ggen from:
--   ontology/zoela/policy.ttl                            (ODRL policies + actions)
--   ontology/profiles/zoela-supabase-rls.ttl             (action → RLS translation)
--   ontology/profiles/zoela-supabase-materialization.ttl (kinds + priorities)
-- Regenerate with: ggen sync --rule zoela-rls
--
-- Doctrine: every CREATE POLICY below corresponds to exactly one ODRL
-- permission tuple joined to an admitted table. Default-deny applies to any
-- (table, operation, role) combination without a row here — ODRL prohibitions
-- are documented in policy.ttl but NOT rendered (their effect is the absence
-- of a grant).
-- =============================================================================

-- ----------------------------------------------------------------------------
-- RLS policy rows: 9
-- (Every row below is an admitted ODRL permission joined to an admitted table.)
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- admin_policy → manage_all_needs (FOR ALL) on push_notification
--   Role:         admin
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
-- ----------------------------------------------------------------------------
CREATE POLICY "admin_policy__manage_all_needs__all__push_notification"
  ON push_notification
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'admin'
        AND pra.is_active = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'admin'
        AND pra.is_active = true
    )
  )
  ;

-- ----------------------------------------------------------------------------
-- volunteer_policy → view_own_assignments (FOR SELECT) on push_notification
--   Role:         volunteer
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
--   Constraint:   auth.uid() = sent_to_person
-- ----------------------------------------------------------------------------
CREATE POLICY "volunteer_policy__view_own_assignments__select__push_notification"
  ON push_notification
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'volunteer'
        AND pra.is_active = true
    )
    AND (auth.uid() = sent_to_person)
  )
  ;

-- ----------------------------------------------------------------------------
-- ministry_lead_policy → view_open_needs (FOR SELECT) on push_notification
--   Role:         ministry_lead
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
-- ----------------------------------------------------------------------------
CREATE POLICY "ministry_lead_policy__view_open_needs__select__push_notification"
  ON push_notification
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'ministry_lead'
        AND pra.is_active = true
    )
  )
  ;

-- ----------------------------------------------------------------------------
-- volunteer_policy → complete_task (FOR UPDATE) on push_notification
--   Role:         volunteer
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
--   Constraint:   auth.uid() = sent_to_person
-- ----------------------------------------------------------------------------
CREATE POLICY "volunteer_policy__complete_task__update__push_notification"
  ON push_notification
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'volunteer'
        AND pra.is_active = true
    )
    AND (auth.uid() = sent_to_person)
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'volunteer'
        AND pra.is_active = true
    )
    AND (auth.uid() = sent_to_person)
  )
  ;

-- ----------------------------------------------------------------------------
-- admin_policy → view_open_needs (FOR SELECT) on push_notification
--   Role:         admin
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
-- ----------------------------------------------------------------------------
CREATE POLICY "admin_policy__view_open_needs__select__push_notification"
  ON push_notification
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'admin'
        AND pra.is_active = true
    )
  )
  ;

-- ----------------------------------------------------------------------------
-- ministry_lead_policy → manage_assignments (FOR ALL) on push_notification
--   Role:         ministry_lead
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
-- ----------------------------------------------------------------------------
CREATE POLICY "ministry_lead_policy__manage_assignments__all__push_notification"
  ON push_notification
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'ministry_lead'
        AND pra.is_active = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'ministry_lead'
        AND pra.is_active = true
    )
  )
  ;

-- ----------------------------------------------------------------------------
-- member_policy → join_serve_opportunity (FOR INSERT) on push_notification
--   Role:         member
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
--   Constraint:   auth.uid() = created_by
-- ----------------------------------------------------------------------------
CREATE POLICY "member_policy__join_serve_opportunity__insert__push_notification"
  ON push_notification
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'member'
        AND pra.is_active = true
    )
    AND (auth.uid() = created_by)
  )
  ;

-- ----------------------------------------------------------------------------
-- ministry_lead_policy → view_follow_ups (FOR SELECT) on push_notification
--   Role:         ministry_lead
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
-- ----------------------------------------------------------------------------
CREATE POLICY "ministry_lead_policy__view_follow_ups__select__push_notification"
  ON push_notification
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'ministry_lead'
        AND pra.is_active = true
    )
  )
  ;

-- ----------------------------------------------------------------------------
-- member_policy → submit_need (FOR INSERT) on push_notification
--   Role:         member
--   Target kind:  ActionMaterialization
--   Source class: https://zoela.org/ontology/PushNotification
--   Constraint:   auth.uid() = created_by
-- ----------------------------------------------------------------------------
CREATE POLICY "member_policy__submit_need__insert__push_notification"
  ON push_notification
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM person_role_assignments pra
      JOIN roles r ON pra.role_id = r.id
      WHERE pra.person_id = auth.uid()::text
        AND r.role_code = 'member'
        AND pra.is_active = true
    )
    AND (auth.uid() = created_by)
  )
  ;

-- =============================================================================
-- End of generated RLS. Default-deny applies to anything not granted above.
-- =============================================================================
