
-- =============================================================================
-- ZOE LA Supabase Body Columns — generated from admissibility-gated extraction
-- =============================================================================
-- DO NOT EDIT. Generated by ggen from:
--   .specify/queries/zoela/extract-public-materialization-columns.rq
--
-- Doctrine: one ALTER TABLE ADD COLUMN per admitted (class, property) tuple.
-- Tables themselves come from zoela-tables.sql; this file adds body columns.
-- Run AFTER zoela-tables.sql.
-- =============================================================================

-- ----------------------------------------------------------------------------
-- Body column rows: 6
-- ----------------------------------------------------------------------------
-- Full body text of the push notification providing context and call-to-action. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS notification_body TEXT;
-- Links a PushNotification to the PersonProfile whose device receives the notification. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS sent_to_person UUID;
-- Category identifier from the NotificationCategoryScheme  used to route and filter notifications in the app. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS notification_category TEXT;
-- Short headline text of the push notification  displayed in the device notification shade. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS notification_title TEXT;
-- Expo deep-link URI that opens the relevant screen in ZOE LA Mobile when the notification is tapped. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS deep_link_route TEXT;
-- Links a PushNotification to the RouteStage whose completion or activation triggered the notification dispatch. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS triggered_by_stage UUID;

-- =============================================================================
-- End of body column additions.
-- =============================================================================
