
-- =============================================================================
-- ZOE LA Supabase Governance — generated from declarative profile
-- =============================================================================
-- DO NOT EDIT. Generated by ggen from:
--   ontology/profiles/zoela-governance.ttl
-- Regenerate with: ggen sync --rule zoela-governance
--
-- These tables are the substrate that zoela-rls.sql subqueries reference.
-- They must apply BEFORE zoela-rls.sql.
--
-- RLS is NOT enabled on these tables: the policy subqueries that gate domain
-- tables read from here, and enabling RLS on roles/person_role_assignments
-- would create a circular dependency. Mutations are restricted at the
-- Postgres role layer (only service_role / postgres can INSERT/UPDATE/DELETE
-- by default).
-- =============================================================================

-- Governance tables: 2

-- ----------------------------------------------------------------------------
-- Person Role Assignment (person_role_assignments)
--   Local class: https://zoela.org/ontology/PersonRoleAssignment
--   Junction binding a Supabase auth.user (person_id) to a role with an active flag. RLS subqueries gate access by checking pra.person_id = auth.uid()::text AND pra.is_active = true.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS person_role_assignments (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  assigned_by TEXT,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_active   BOOLEAN     NOT NULL DEFAULT true,
  role_id     UUID        NOT NULL REFERENCES roles(id),
  person_id   TEXT        NOT NULL
);

CREATE TRIGGER set_person_role_assignments_updated_at
  BEFORE UPDATE ON person_role_assignments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ----------------------------------------------------------------------------
-- Role (roles)
--   Local class: https://zoela.org/ontology/Role
--   Application role used by RLS subqueries. Each row is a (role_code, label) pair referenced by person_role_assignments.role_id.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS roles (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  description TEXT,
  role_label  TEXT        NOT NULL,
  role_code   TEXT        NOT NULL UNIQUE
);

CREATE TRIGGER set_roles_updated_at
  BEFORE UPDATE ON roles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Seed rows for roles (4 rows)
INSERT INTO roles (role_code, role_label, description) VALUES
  ('admin', 'Admin', 'Full administrative access'),
  ('ministry_lead', 'Ministry Lead', 'Leads a ministry and can manage assignments'),
  ('volunteer', 'Volunteer', 'Member who has accepted at least one serve opportunity'),
  ('member', 'Member', 'Standard authenticated member of the congregation')
ON CONFLICT (role_code) DO NOTHING;

-- =============================================================================
-- End of governance migration. zoela-rls.sql may now reference these tables.
-- =============================================================================
