PREFIX truex: <https://open-ontologies.org/profile/truex#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?artifact ?path ?label WHERE {
  ?artifact a truex:Artifact ;
            truex:path ?path ;
            rdfs:label ?label .
}
ORDER BY ?path
