
// ============================================================
// DO NOT EDIT — generated by ggen from
//   ontology/zoela/navigation.ttl + extract-admin-screens.rq
// Regenerate: ggen sync --rule zoela-admin-screens
// ============================================================

import React from 'react';
import { View, Text, FlatList, StyleSheet } from 'react-native';

// Admin list screens: 3

// ----------------------------------------------------------------
// Admin: Open Needs (object: needs, role: CARE)
// ----------------------------------------------------------------
export function AdminOpenNeedsScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Admin: Open Needs</Text>
      <Text style={styles.subtitle}>filter: needs · role: CARE</Text>
    </View>
  );
}

// ----------------------------------------------------------------
// Admin: Pending Receipts (object: receipts, role: ADMIN)
// ----------------------------------------------------------------
export function AdminPendingReceiptsScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Admin: Pending Receipts</Text>
      <Text style={styles.subtitle}>filter: receipts · role: ADMIN</Text>
    </View>
  );
}

// ----------------------------------------------------------------
// Admin: Follow-Ups Overdue (object: follow_up_tasks, role: CARE)
// ----------------------------------------------------------------
export function AdminFollowUpsOverdueScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Admin: Follow-Ups Overdue</Text>
      <Text style={styles.subtitle}>filter: follow_up_tasks · role: CARE</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  title:     { fontSize: 20, fontWeight: 'bold', marginBottom: 6 },
  subtitle:  { fontSize: 12, color: '#666' },
});
