
// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/navigation.ttl + extract-admin-screens.rq
// Regenerate with: ggen sync --rule zoela-admin-detail

import React from 'react';
import { ScrollView, Text, View, StyleSheet } from 'react-native';

// Admin Detail: Admin: Follow-Ups Overdue
// Object type:  follow_up_tasks
// Route:        AdminFollowUpsOverdue
export function AdminFollowUpsOverdueDetailScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Admin: Follow-Ups Overdue</Text>
      {/* Tab: ADMIN */}
      {/* Stack: AdminStack */}
      {/* Required role: CARE */}
      {/* Object type: follow_up_tasks */}
      <View style={styles.content}>
        <Text style={styles.placeholder}>
          follow_up_tasks detail view
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container:   { flex: 1, backgroundColor: '#fff' },
  content:     { padding: 16 },
  title:       { fontSize: 22, fontWeight: '700', paddingHorizontal: 16, paddingTop: 16, marginBottom: 8 },
  placeholder: { fontSize: 14, color: '#666', fontStyle: 'italic' },
});
