
// ============================================================
// DO NOT EDIT — generated by ggen from
//   ontology/zoela/navigation.ttl + extract-admin-screens.rq
// Regenerate: ggen sync --rule zoela-admin-detail
// ============================================================

import React from 'react';
import { ScrollView, Text, View, StyleSheet } from 'react-native';

// Admin detail screens: 3

// ----------------------------------------------------------------
// Admin: Open Needs
//   tab:    ADMIN · stack: AdminStack · role: CARE
//   object: needs
// ----------------------------------------------------------------
export function AdminOpenNeedsDetailScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Admin: Open Needs</Text>
      <View style={styles.content}>
        <Text style={styles.placeholder}>needs detail view</Text>
      </View>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Admin: Pending Receipts
//   tab:    ADMIN · stack: AdminStack · role: ADMIN
//   object: receipts
// ----------------------------------------------------------------
export function AdminPendingReceiptsDetailScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Admin: Pending Receipts</Text>
      <View style={styles.content}>
        <Text style={styles.placeholder}>receipts detail view</Text>
      </View>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Admin: Follow-Ups Overdue
//   tab:    ADMIN · stack: AdminStack · role: CARE
//   object: follow_up_tasks
// ----------------------------------------------------------------
export function AdminFollowUpsOverdueDetailScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Admin: Follow-Ups Overdue</Text>
      <View style={styles.content}>
        <Text style={styles.placeholder}>follow_up_tasks detail view</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container:   { flex: 1, backgroundColor: '#fff' },
  content:     { padding: 16 },
  title:       { fontSize: 22, fontWeight: '700', paddingHorizontal: 16, paddingTop: 16, marginBottom: 8 },
  placeholder: { fontSize: 14, color: '#666', fontStyle: 'italic' },
});
