
// ============================================================
// DO NOT EDIT THIS FILE
//
// This file is auto-generated by ggen from:
//   ontology/zoela/navigation.ttl + extract-screens.rq
//
// Regenerate with: ggen sync --rule zoela-screens
// Every export below corresponds to one zoe:AppScreen instance.
// ============================================================

import React from 'react';
import { ScrollView, Text, StyleSheet } from 'react-native';

// Screen exports: 14

// ----------------------------------------------------------------
// Admin: Open Needs
//   id:       admin_open_needs
//   nav:      AdminOpenNeeds
//   tab:      ADMIN  stack: AdminStack
//   role:     CARE  ADMIN-ONLY
//   object:   needs
//   category: CARE
// ----------------------------------------------------------------
export function AdminOpenNeedsScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Admin: Open Needs</Text>
      <Text style={styles.subtitle}>ADMIN · CARE · admin</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Care Requests
//   id:       care_request_list
//   nav:      CareRequestList
//   tab:      CARE  stack: CareStack
//   role:     CARE
//   object:   care_requests
//   category: CARE
// ----------------------------------------------------------------
export function CareRequestListScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Care Requests</Text>
      <Text style={styles.subtitle}>CARE · CARE</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Connect Groups
//   id:       connect_group_list
//   nav:      ConnectGroupList
//   tab:      GROUPS  stack: GroupsStack
//   role:     MEMBER
//   object:   connect_groups
// ----------------------------------------------------------------
export function ConnectGroupListScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Connect Groups</Text>
      <Text style={styles.subtitle}>GROUPS · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Events
//   id:       event_list
//   nav:      EventList
//   tab:      EVENTS  stack: EventsStack
//   role:     MEMBER
//   object:   events
// ----------------------------------------------------------------
export function EventListScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Events</Text>
      <Text style={styles.subtitle}>EVENTS · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Home Feed
//   id:       home_feed
//   nav:      HomeFeed
//   tab:      HOME  stack: HomeStack
//   role:     MEMBER
// ----------------------------------------------------------------
export function HomeFeedScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Home Feed</Text>
      <Text style={styles.subtitle}>HOME · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Volunteer Opportunities
//   id:       volunteer_opportunities
//   nav:      VolunteerOpportunities
//   tab:      SERVE  stack: ServeStack
//   role:     MEMBER
//   object:   volunteer_opportunities
// ----------------------------------------------------------------
export function VolunteerOpportunitiesScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Volunteer Opportunities</Text>
      <Text style={styles.subtitle}>SERVE · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Admin: Pending Receipts
//   id:       admin_pending_receipts
//   nav:      AdminPendingReceipts
//   tab:      ADMIN  stack: AdminStack
//   role:     ADMIN  ADMIN-ONLY
//   object:   receipts
// ----------------------------------------------------------------
export function AdminPendingReceiptsScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Admin: Pending Receipts</Text>
      <Text style={styles.subtitle}>ADMIN · ADMIN · admin</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Connect Groups Home
//   id:       connect_groups_home
//   nav:      ConnectGroupsHome
//   tab:      GROUPS  stack: GroupsStack
//   role:     MEMBER
//   object:   connect_groups
// ----------------------------------------------------------------
export function ConnectGroupsHomeScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Connect Groups Home</Text>
      <Text style={styles.subtitle}>GROUPS · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Event Detail
//   id:       event_detail
//   nav:      EventDetail
//   tab:      EVENTS  stack: EventsStack
//   role:     MEMBER
//   object:   events
// ----------------------------------------------------------------
export function EventDetailScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Event Detail</Text>
      <Text style={styles.subtitle}>EVENTS · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// New Care Request
//   id:       new_care_request
//   nav:      NewCareRequest
//   tab:      CARE  stack: CareStack
//   role:     MEMBER
//   object:   care_requests
// ----------------------------------------------------------------
export function NewCareRequestScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>New Care Request</Text>
      <Text style={styles.subtitle}>CARE · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Admin: Follow-Ups Overdue
//   id:       admin_followups_overdue
//   nav:      AdminFollowUpsOverdue
//   tab:      ADMIN  stack: AdminStack
//   role:     CARE  ADMIN-ONLY
//   object:   follow_up_tasks
// ----------------------------------------------------------------
export function AdminFollowUpsOverdueScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Admin: Follow-Ups Overdue</Text>
      <Text style={styles.subtitle}>ADMIN · CARE · admin</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Connect Group Detail
//   id:       connect_group_detail
//   nav:      ConnectGroupDetail
//   tab:      GROUPS  stack: GroupsStack
//   role:     MEMBER
//   object:   connect_groups
// ----------------------------------------------------------------
export function ConnectGroupDetailScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Connect Group Detail</Text>
      <Text style={styles.subtitle}>GROUPS · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// My Groups
//   id:       my_groups
//   nav:      MyGroups
//   tab:      GROUPS  stack: GroupsStack
//   role:     MEMBER
//   object:   connect_groups
// ----------------------------------------------------------------
export function MyGroupsScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>My Groups</Text>
      <Text style={styles.subtitle}>GROUPS · MEMBER</Text>
    </ScrollView>
  );
}

// ----------------------------------------------------------------
// Group Interest Form
//   id:       group_interest_form
//   nav:      GroupInterestForm
//   tab:      GROUPS  stack: GroupsStack
//   role:     MEMBER
//   object:   connect_groups
// ----------------------------------------------------------------
export function GroupInterestFormScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>Group Interest Form</Text>
      <Text style={styles.subtitle}>GROUPS · MEMBER</Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  title:     { fontSize: 24, fontWeight: 'bold', padding: 16 },
  subtitle:  { fontSize: 12, color: '#666', paddingHorizontal: 16, paddingBottom: 8 },
});
