// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/ocel.ttl + extract-ocel-schema.rq
// Compatible with wasm4pm OCEL 2.0 process mining format







export interface OcelSchema {
  objectTypes: string[];
  eventTypes: string[];
  objectAttributes: string[];
  eventAttributes: string[];
  objectRelationships: string[];
}

export const ZOELA_OCEL_SCHEMA: OcelSchema = {
  objectTypes: [

    "Person",

    "ServiceRoute",

    "Need",

    "Resource",

    "Volunteer",

  ],
  eventTypes: [

    "Baptism Registered",

    "Event Attendance Recorded",

    "Guardian Consent Required",

    "Route Refused",

    "Receipt Emitted",

    "Care Route Closed",

    "Partner Referral Sent",

    "Follow-Up Completed",

    "Follow-Up Scheduled",

    "Clothing Delivered",

    "Food Delivered",

    "Volunteer Assigned",

    "Consent Granted",

    "Need Refused",

    "Need Closed",

    "Need Delivered",

    "Need Assigned",

    "Need Received",

  ],
  objectAttributes: [

    "personId",

    "routeId",

    "needCategory",

  ],
  eventAttributes: [

    "timestamp",

    "stageCode",

    "actorId",

    "routeId",

  ],
  objectRelationships: [

    "Person-ServiceRoute",

    "ServiceRoute-Need",

    "ServiceRoute-Resource",

  ],
};

// wasm4pm process mining integration
export function toOcelEventLog(events: Array<{type: string; objectId: string; timestamp: string}>) {
  return {
    ocel_version: '2.0',
    ocel_global_event: { ocel_activity: '__INVALID__' },
    ocel_global_object: { ocel_type: '__INVALID__' },
    ocel_global_log: {
      ocel_attribute_names: ZOELA_OCEL_SCHEMA.eventAttributes,
      ocel_object_types: ZOELA_OCEL_SCHEMA.objectTypes,
    },
    ocel_events: events.reduce((acc, e) => ({
      ...acc,
      [`${e.objectId}-${e.timestamp}`]: {
        ocel_activity: e.type,
        ocel_timestamp: e.timestamp,
        ocel_omap: [e.objectId],
        ocel_vmap: {},
      }
    }), {}),
    ocel_objects: {},
  };
}
