// ============================================================
// DO NOT EDIT THIS FILE
//
// This file is auto-generated by ggen from:
//   ontology/zoela/autoreceipt.ttl
//
// Regenerate with: ggen sync --rule zoela-autoreceipt-ts
// ============================================================

/**
 * Typestates for AutoReceiptPipeline — generated from ontology/zoela/autoreceipt.ttl
 */// Define the precise allowable states
export type AutoReceiptPipelineState =
  | "ArchitecturalReceiptParsed"
  | "ExpectedOcelManufactured"
  | "ExecutionRegistryBound"
  | "ObservedOcelCaptured"
  | "AlignmentVerified"
  | "ReceiptEmitted";

/**
 * The AutoReceiptPipeline state machine.
 * Enforces the Chatman Equation (A = μ(O)) in TypeScript.
 */
export class AutoReceiptPipeline<S extends AutoReceiptPipelineState> {
  // Use a private constructor to prevent arbitrary instantiation
  private constructor(
    public readonly state: S,
    public readonly executionContext: Record<string, any>
  ) {}

  /**
   * Initialize the state machine in the starting state.
   */
  static new(initialContext: Record<string, any> = {}): AutoReceiptPipeline<"ArchitecturalReceiptParsed"> {
    return new AutoReceiptPipeline("ArchitecturalReceiptParsed", initialContext);
  }

  transition(contextUpdate?: Record<string, any>): AutoReceiptPipeline<any> {
    const nextStates: Record<AutoReceiptPipelineState, AutoReceiptPipelineState> = {
      "ArchitecturalReceiptParsed": "ExpectedOcelManufactured",
      "ExpectedOcelManufactured": "ExecutionRegistryBound",
      "ExecutionRegistryBound": "ObservedOcelCaptured",
      "ObservedOcelCaptured": "AlignmentVerified",
      "AlignmentVerified": "ReceiptEmitted",
      "ReceiptEmitted": "ReceiptEmitted"
    };
    return new AutoReceiptPipeline(nextStates[this.state as AutoReceiptPipelineState], { ...this.executionContext, ...contextUpdate });
  }
  
  
}
