
// ============================================================
// DO NOT EDIT — generated by ggen for zoela-la-mobile
// Source: .specify/templates/zoela/expo-babel-config.tera
// ============================================================

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
};
