#!/usr/bin/env bash
set -eo pipefail

DURATION=600
END_TIME=$((SECONDS + DURATION))

echo "Running Gemini CLI fully auto loop for $DURATION seconds (10 minutes)..."

mkdir -p artifacts/actuation/plans
cat << 'EOF' > artifacts/actuation/plans/loop_plan.json
{
  "emitted_by": "open-ontologies",
  "policy_id": "auto_loop_policy",
  "action_id": "auto_loop_action",
  "allowed": true,
  "working_directory": "/Users/sac/open-ontologies",
  "prompt": "echo 'Auto loop execution'"
}
EOF

COUNT=0
while [ $SECONDS -lt $END_TIME ]; do
  bash scripts/actuation/oo-gemini-actuate.sh artifacts/actuation/plans/loop_plan.json > /dev/null 2>&1 || true
  COUNT=$((COUNT + 1))
  echo "Executed loop iteration $COUNT at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  sleep 10
done

echo "Loop completed after 10 minutes. Ran $COUNT times."
echo "Generating OCEL report..."

mkdir -p artifacts/autoreceipt
python3 -c "
import glob, json
receipts = glob.glob('$(pwd)/artifacts/actuation/receipts/*.json')
events = []
for r in receipts:
    try:
        with open(r) as f:
            data = json.load(f)
            # Only track events generated by this loop (or all of them for the report)
            if data.get('action_id') == 'auto_loop_action':
                events.append({
                    'ocel:activity': 'AutoLoopExecution',
                    'ocel:timestamp': data.get('created_at', ''),
                    'ocel:vmap': {
                        'exit_code': data.get('exit_code'),
                        'stdout_hash': data.get('stdout_hash')
                    }
                })
    except Exception as e:
        pass

report = {
    'ocel:global-log': {'ocel:object-types': ['schema:Action']},
    'ocel:events': events
}

with open('artifacts/autoreceipt/auto_loop_ocel_report.json', 'w') as f:
    json.dump(report, f, indent=2)

print(f'Successfully compiled {len(events)} execution traces into OCEL report.')
"

echo "OCEL Report generated at artifacts/autoreceipt/auto_loop_ocel_report.json"
cat artifacts/autoreceipt/auto_loop_ocel_report.json
