
// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/routes.ttl + extract-service-routes.rq
// Regenerate with: ggen sync --rule zoela-service-routes

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

type StageTransitionResult = { ok: boolean; receiptType?: string; error?: string };

const STAGE_HANDLERS: Record<string, (routeId: string, stageId: string, actorId: string) => Promise<StageTransitionResult>> = {

  // Route: FOOD_DIST_V1 | Stage: Received
  "FOOD_DIST_V1:received": async (routeId, stageId, actorId) => {
    
    // Requires role: MemberRole
    console.log(`[FOOD_DIST_V1] Received — routeId=${routeId} stageId=${stageId} actor=${actorId}`);
    return { ok: true };
  },

  // Route: FOOD_DIST_V1 | Stage: Verified
  "FOOD_DIST_V1:verified": async (routeId, stageId, actorId) => {
    
    // Requires role: VolunteerRole
    console.log(`[FOOD_DIST_V1] Verified — routeId=${routeId} stageId=${stageId} actor=${actorId}`);
    return { ok: true };
  },

  // Route: FOOD_DIST_V1 | Stage: Assigned
  "FOOD_DIST_V1:assigned": async (routeId, stageId, actorId) => {
    
    // Requires role: VolunteerRole
    console.log(`[FOOD_DIST_V1] Assigned — routeId=${routeId} stageId=${stageId} actor=${actorId}`);
    return { ok: true };
  },

  // Route: FOOD_DIST_V1 | Stage: Delivered
  "FOOD_DIST_V1:delivered": async (routeId, stageId, actorId) => {
    
    // Requires role: VolunteerRole
    console.log(`[FOOD_DIST_V1] Delivered — routeId=${routeId} stageId=${stageId} actor=${actorId}`);
    return { ok: true, receiptType: 'ResourceDistributedReceipt' };
  },

  // Route: FOOD_DIST_V1 | Stage: Closed
  "FOOD_DIST_V1:closed": async (routeId, stageId, actorId) => {
    
    
    console.log(`[FOOD_DIST_V1] Closed — routeId=${routeId} stageId=${stageId} actor=${actorId}`);
    return { ok: true, receiptType: 'CareRouteClosedReceipt' };
  },

};

serve(async (req: Request) => {
  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
  );

  let body: { routeCode: string; routeId: string; stageCode: string; actorId: string };
  try {
    body = await req.json();
  } catch {
    return new Response('Invalid JSON body', { status: 400 });
  }

  const { routeCode, routeId, stageCode, actorId } = body;
  const handlerKey = `${routeCode}:${stageCode}`;
  const handler = STAGE_HANDLERS[handlerKey];

  if (!handler) {
    return new Response(
      JSON.stringify({ ok: false, error: `Unknown route:stage — ${handlerKey}` }),
      { status: 404, headers: { 'Content-Type': 'application/json' } },
    );
  }

  const result = await handler(routeId, stageCode, actorId);
  return new Response(JSON.stringify(result), {
    status: result.ok ? 200 : 422,
    headers: { 'Content-Type': 'application/json' },
  });
});
