#!/bin/bash
# gh-create-issue.sh — Generated by ggen
# Create a formal work order issue using the GitHub CLIJTBD_ID=$1
PERSONA=$2
SUMMARY=$3

if [ -z "$JTBD_ID" ] || [ -z "$PERSONA" ] || [ -z "$SUMMARY" ]; then
  echo "Usage: $0 <JTBD_ID> <PERSONA> <SUMMARY>"
  exit 1
fi

echo "Creating issue in open-ontologies..."

gh issue create \
  --repo "open-ontologies" \
  --title "[$JTBD_ID] $SUMMARY" \
  --body "## Work Order Details
- **Persona**: $PERSONA
- **JTBD**: $JTBD_ID
- **Status**: Admitted
- **Law**: R ⊢ A = μ(O*)

## Summary
$SUMMARY" \
  --label "work-order"
