#!/bin/bash
# gh-create-pr.sh — Generated by ggen
# Create a PR that automatically references the receipt and JTBD

export GH_NO_UPDATE_NOTIFIER=1

JTBD_ID=$1
RECEIPT_HASH=$2

if [ -z "$JTBD_ID" ] || [ -z "$RECEIPT_HASH" ]; then
  echo "Usage: $0 <JTBD_ID> <RECEIPT_HASH>"
  exit 1
fi

echo "Creating PR for fabio-rovai/open-ontologies..."

gh pr create \
  --repo "fabio-rovai/open-ontologies" \
  --title "[$JTBD_ID] Implementation Proof" \
  --body "## Implementation Summary
Closes issue referencing $JTBD_ID.

## Cryptographic Proof
- **Receipt Hash**: $RECEIPT_HASH
- **Relation**: R ⊢ A = μ(O*)

This PR was generated with validated observed OCEL and alignment receipts."
