#!/usr/bin/env python3
"""
manufacture_cli.py — Tier 2 manufacturing step for open-ontologies CLI

Reads ontology/cli-open-ontologies.ttl (Tier 1) and generates
src/cmds/generated.rs (Tier 3) via SPARQL extraction + Tera-compatible
template rendering.

Run with: python3 scripts/manufacture_cli.py
Alternatively driven by: ggen sync (requires ggen v5+ with vocabulary bypass)

Three-tier architecture:
  Tier 1 — ontology/cli-open-ontologies.ttl   (source of truth)
  Tier 2 — this script                         (manufacturing)
  Tier 3 — src/cmds/generated.rs              (generated CLI stubs)
"""

from pathlib import Path
from typing import cast
from rdflib import Graph, Namespace, RDF, URIRef
from rdflib.term import Node

CLI = Namespace("https://ggen.io/onto/cli/spec/")
ONTO = Namespace("https://ggen.io/onto/cli/open-ontologies/")

ONTOLOGY_PATH = Path("ontology/cli-open-ontologies.ttl")
OUTPUT_PATH = Path("src/cmds/generated.rs")

HEADER = """\
// ============================================================
// DO NOT EDIT THIS FILE
//
// This file is auto-generated by ggen from:
//   ontology/cli-open-ontologies.ttl
//
// Regenerate with: ggen sync
// (or: python3 scripts/manufacture_cli.py)
//
// Three-tier architecture:
//   Tier 1 — ontology/cli-open-ontologies.ttl  (source of truth)
//   Tier 2 — ggen sync / manufacture_cli.py    (manufacturing)
//   Tier 3 — src/cmds/generated.rs             (this file)
// ============================================================
"""


def snake(name: str) -> str:
    """Convert a kebab-case name to snake_case."""
    return name.replace("-", "_")


def get_str(g: Graph, subject: Node, predicate) -> str | None:
    val = g.value(subject, predicate)
    return str(val) if val is not None else None


def get_options(g: Graph, cmd: Node) -> list[dict]:
    """Extract all options for a command."""
    options = []
    for opt in g.objects(cmd, CLI.hasOption):
        name = get_str(g, opt, CLI.name) or ""
        long_name = get_str(g, opt, CLI.longName) or f"--{name}"
        summary = get_str(g, opt, CLI.summary) or ""
        required_lit = g.value(opt, CLI.required)
        required = str(required_lit).lower() == "true" if required_lit else False
        global_lit = g.value(opt, CLI["global"])
        is_global = str(global_lit).lower() == "true" if global_lit else False

        # Determine type: Flag or ValueOption
        if (opt, RDF.type, CLI.Flag) in g:
            opt_type = "flag"
        else:
            opt_type = "value"

        options.append({
            "name": name,
            "long_name": long_name,
            "summary": summary,
            "required": required,
            "global": is_global,
            "type": opt_type,
        })

    # Sort by name for deterministic output
    options.sort(key=lambda x: x["name"])
    return options


def get_positional_args(g: Graph, cmd: Node) -> list[dict]:
    """Extract positional arguments for a command."""
    args = []
    for parg in g.objects(cmd, CLI.hasPositionalArgument):
        name = get_str(g, parg, CLI.name) or ""
        summary = get_str(g, parg, CLI.summary) or ""
        required_lit = g.value(parg, CLI.required)
        required = str(required_lit).lower() == "true" if required_lit else True
        args.append({
            "name": name,
            "summary": summary,
            "required": required,
        })
    return args


def render_verb_params(options: list[dict], positional_args: list[dict]) -> str:
    """Render Rust function parameters for a verb."""
    params = []

    # Positional args first
    for arg in positional_args:
        param_name = snake(arg["name"])
        if arg["required"]:
            params.append(f"        {param_name}: String")
        else:
            params.append(f"        {param_name}: Option<String>")

    # Options (non-global)
    for opt in options:
        if opt["global"]:
            continue
        param_name = snake(opt["name"])
        if opt["type"] == "flag":
            params.append(f"        {param_name}: bool")
        elif opt["required"]:
            params.append(f"        {param_name}: String")
        else:
            params.append(f"        {param_name}: Option<String>")

    return ",\n".join(params)


def render_noun_module(noun_name: str, summary: str, subcommands: list[dict]) -> str:
    """Render one noun module with all its verb stubs."""
    lines = []
    lines.append(f"// ============================================================================")
    lines.append(f"// {noun_name.upper()} — {summary}")
    lines.append(f"// ============================================================================")
    lines.append(f"")
    lines.append(f"#[allow(dead_code, unused_variables)]")
    lines.append(f"pub mod {snake(noun_name)} {{")
    lines.append(f"    use clap_noun_verb::Result as NounVerbResult;")
    lines.append(f"    use clap_noun_verb_macros::verb;")
    lines.append(f"    use serde::Serialize;")

    for sub in subcommands:
        verb_name = sub["name"]
        verb_summary = sub["summary"]
        options = sub["options"]
        positional_args = sub["positional_args"]

        lines.append(f"")
        lines.append(f"    /// {verb_summary}")
        lines.append(f"    #[verb]")

        params = render_verb_params(options, positional_args)
        if params:
            lines.append(f"    pub fn {snake(verb_name)}(")
            for p in params.split(",\n"):
                lines.append(f"    {p.rstrip()},")
            lines.append(f"    ) -> NounVerbResult<serde_json::Value> {{")
        else:
            lines.append(f"    pub fn {snake(verb_name)}() -> NounVerbResult<serde_json::Value> {{")

        lines.append(f'        todo!("wire {noun_name}::{verb_name} to open_ontologies lib")')
        lines.append(f"    }}")

    lines.append(f"}}")
    lines.append(f"")
    return "\n".join(lines)


def manufacture(ontology_path: Path, output_path: Path) -> None:
    """Load ontology and manufacture the generated.rs file."""
    print(f"Loading ontology: {ontology_path}")
    g = Graph()
    g.parse(str(ontology_path), format="turtle")
    print(f"Loaded {len(g)} triples")

    # Find the interface
    interface = ONTO.OntoInterface
    interface_name = get_str(g, interface, CLI.name) or "open-ontologies"

    # Get top-level commands
    command_uris = list(g.objects(interface, CLI.hasCommand))

    # Build command data
    commands = []
    for cmd_uri in command_uris:
        cmd_node = cast(URIRef, cmd_uri)
        noun_name = get_str(g, cmd_node, CLI.name) or ""
        noun_summary = get_str(g, cmd_node, CLI.summary) or ""

        # Get subcommands
        sub_uris = list(g.objects(cmd_node, CLI.hasSubcommand))
        subcommands = []
        for sub_uri in sub_uris:
            sub_node = cast(URIRef, sub_uri)
            verb_name = get_str(g, sub_node, CLI.name) or ""
            verb_summary = get_str(g, sub_node, CLI.summary) or ""
            options = get_options(g, sub_node)
            positional_args = get_positional_args(g, sub_node)
            subcommands.append({
                "name": verb_name,
                "summary": verb_summary,
                "options": options,
                "positional_args": positional_args,
            })

        # Sort subcommands by name
        subcommands.sort(key=lambda x: x["name"])

        commands.append({
            "name": noun_name,
            "summary": noun_summary,
            "subcommands": subcommands,
        })

    # Sort commands by name
    commands.sort(key=lambda x: x["name"])

    # Render output
    sections = [HEADER]
    sections.append(f"//! {interface_name} CLI — generated command stubs")
    sections.append(f"//!")
    sections.append(f"//! Generated by ggen from ontology/cli-open-ontologies.ttl")
    sections.append(f"//! Do not edit — regenerate with: ggen sync")
    sections.append(f"//!")
    sections.append(f"//! Architecture:")
    sections.append(f"//!   Tier 1  — ontology/cli-open-ontologies.ttl   (source of truth)")
    sections.append(f"//!   Tier 2  — ggen sync / manufacture_cli.py     (manufacturing step)")
    sections.append(f"//!   Tier 3  — src/cmds/generated.rs              (this file, wired to lib)")
    sections.append(f"")
    sections.append(f"#![allow(dead_code, unused_variables, unreachable_code)]")
    sections.append(f"")

    for cmd in commands:
        if cmd["subcommands"]:
            sections.append(render_noun_module(cmd["name"], cmd["summary"], cmd["subcommands"]))

    output = "\n".join(sections)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output)
    print(f"Generated: {output_path}")
    print(f"  Commands: {len(commands)}")
    print(f"  Total verbs: {sum(len(c['subcommands']) for c in commands)}")


if __name__ == "__main__":
    manufacture(ONTOLOGY_PATH, OUTPUT_PATH)
