#!/usr/bin/env python3
"""Deterministically render the GitHub Actions CI projection.

Authority chain:
    ci/ggen-ci.toml -> tools/ggen_ci.py -> .github/workflows/ci.yml

The renderer has no network or third-party Python dependencies. Generated output
must be changed through the manifest or this renderer, never by editing the YAML
projection directly.
"""

from __future__ import annotations

import argparse
import difflib
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "ci" / "ggen-ci.toml"
EXPECTED_SCHEMA = "chatmangpt.ggen-ci/v1"


def load_manifest(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        manifest = tomllib.load(handle)
    if manifest.get("schema") != EXPECTED_SCHEMA:
        raise ValueError(
            f"unsupported CI schema {manifest.get('schema')!r}; expected {EXPECTED_SCHEMA!r}"
        )
    required = (
        "workflow_name",
        "source",
        "generator",
        "generated_workflow",
        "toolchain",
        "actions",
        "admission",
        "verification",
        "portable",
        "real_toolchain",
        "groq",
    )
    missing = [key for key in required if key not in manifest]
    if missing:
        raise ValueError(f"missing manifest keys: {', '.join(missing)}")
    return manifest


def indent_commands(commands: list[str], spaces: int = 10) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" for command in commands for line in command.splitlines())


def render(manifest: dict[str, Any]) -> str:
    workflow_name = str(manifest["workflow_name"])
    source = str(manifest["source"])
    generator = str(manifest["generator"])
    rust = str(manifest["toolchain"]["rust"])
    python = str(manifest["toolchain"]["python"])
    checkout = str(manifest["actions"]["checkout"])
    setup_python = str(manifest["actions"]["setup_python"])

    admission_commands = [str(value) for value in manifest["admission"]["commands"]]
    if len(admission_commands) != 4:
        raise ValueError("admission.commands must contain exactly four ordered gates")
    portable_os = [str(value) for value in manifest["portable"]["os"]]
    portable_commands = [str(value) for value in manifest["portable"]["commands"]]
    real_os = [str(value) for value in manifest["real_toolchain"]["os"]]
    real_test = str(manifest["real_toolchain"]["test"])
    verification = str(manifest["verification"]["command"])
    groq_tests = [str(value) for value in manifest["groq"]["tests"]]

    portable_matrix = ", ".join(portable_os)
    real_matrix = ", ".join(real_os)
    portable_run = indent_commands(portable_commands, 10)
    groq_loop = " ".join(groq_tests)

    output = f'''# @generated by {generator} from {source}; DO NOT EDIT.
name: {workflow_name}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ggen-ci-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  admission:
    name: admitted exact tree
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@{checkout}
      - uses: actions/setup-python@{setup_python}
        with:
          python-version: '{python}'
      - name: Install pinned toolchain
        shell: bash
        run: |
          rustup toolchain install '{rust}' --profile minimal --component rustfmt --component clippy
          rustup default '{rust}'
      - name: Verify pinned toolchain
        shell: bash
        run: rustup show active-toolchain | grep -F '{rust}'
      - name: Verify generated CI replay
        run: {admission_commands[0]}
      - name: Verify repository constitution
        run: {admission_commands[1]}
      - name: Verify authored Rust formatting
        run: {admission_commands[2]}
      - name: Verify locked dependency graph
        run: {admission_commands[3]}

  verification:
    name: unit integration e2e adversarial
    needs: admission
    runs-on: ubuntu-22.04
    env:
      GITHUB_PR_LABELS: ${{{{ join(github.event.pull_request.labels.*.name, ',') }}}}
    steps:
      - uses: actions/checkout@{checkout}
      - name: Run ggen verification matrix
        run: {verification}

  portable:
    name: portable (${{{{ matrix.os }}}})
    needs: admission
    strategy:
      fail-fast: false
      matrix:
        os: [{portable_matrix}]
    runs-on: ${{{{ matrix.os }}}}
    steps:
      - uses: actions/checkout@{checkout}
      - name: Check and test portable core
        shell: bash
        run: |
{portable_run}

  real-toolchain-smoke:
    name: real toolchain (${{{{ matrix.os }}}})
    needs: admission
    strategy:
      fail-fast: false
      matrix:
        os: [{real_matrix}]
    runs-on: ${{{{ matrix.os }}}}
    steps:
      - uses: actions/checkout@{checkout}
      - name: Install Erlang and Terraform on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y erlang
          wget -qO- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y terraform
      - name: Install Erlang and Terraform on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: brew install erlang terraform
      - name: Execute real-toolchain falsifiers
        shell: bash
        run: {real_test}

  real-groq-sweep:
    name: real Groq sweep (optional external boundary)
    needs: verification
    runs-on: ubuntu-22.04
    continue-on-error: true
    env:
      GROQ_API_KEY: ${{{{ secrets.GROQ_API_KEY }}}}
    steps:
      - uses: actions/checkout@{checkout}
      - name: Execute configured real-Groq tests
        shell: bash
        run: |
          if [[ -z "${{GROQ_API_KEY:-}}" ]]; then
            echo "GROQ_API_KEY absent; external Groq standing remains UNKNOWN."
            exit 0
          fi
          for test_name in {groq_loop}; do
            cargo test --locked --test "$test_name" -- --nocapture --test-threads=1
          done
          cargo test --locked --test revops_e2e_with_real_groq -- --ignored --nocapture --test-threads=1
'''
    return output


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the generated workflow")
    mode.add_argument("--stdout", action="store_true", help="print the generated workflow")
    mode.add_argument("--check", action="store_true", help="verify the committed workflow")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest_path = args.manifest.resolve()
    manifest = load_manifest(manifest_path)
    rendered = render(manifest)
    output_path = ROOT / str(manifest["generated_workflow"])

    if args.stdout:
        sys.stdout.write(rendered)
        return 0
    if args.write:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered, encoding="utf-8")
        return 0

    committed = output_path.read_text(encoding="utf-8") if output_path.is_file() else ""
    if committed == rendered:
        print(f"ggen CI projection verified: {output_path.relative_to(ROOT)}")
        return 0

    diff = difflib.unified_diff(
        committed.splitlines(),
        rendered.splitlines(),
        fromfile=str(output_path.relative_to(ROOT)),
        tofile=f"generated:{output_path.relative_to(ROOT)}",
        lineterm="",
    )
    print("\n".join(diff), file=sys.stderr)
    print(f"CI projection drift: run {manifest['generator']} --write", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
