#!/usr/bin/env python3
"""Independently verify the ggen-owned CI projection and deterministic replay."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "ci" / "ggen-ci.toml"
RENDERER = ROOT / "tools" / "ggen_ci.py"
WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"
LEGACY_WORKFLOW = ROOT / ".github" / "workflows" / "regression-gates.yml"


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def render(manifest: Path) -> bytes:
    completed = subprocess.run(
        [sys.executable, str(RENDERER), "--manifest", str(manifest), "--stdout"],
        cwd=ROOT,
        check=False,
        capture_output=True,
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr.decode("utf-8", errors="replace"))
    return completed.stdout


def check(name: str, passed: bool, **evidence: object) -> dict[str, object]:
    return {"name": name, "passed": passed, "evidence": evidence}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    checks: list[dict[str, object]] = []
    errors: list[str] = []

    try:
        first = render(MANIFEST)
        second = render(MANIFEST)
        committed = WORKFLOW.read_bytes()

        checks.append(
            check(
                "deterministic replay",
                first == second,
                first_sha256=digest(first),
                second_sha256=digest(second),
            )
        )
        checks.append(
            check(
                "committed projection matches manufacture",
                committed == first,
                committed_sha256=digest(committed),
                manufactured_sha256=digest(first),
            )
        )

        with tempfile.TemporaryDirectory(prefix="ggen-ci-falsifier-") as directory:
            mutated = Path(directory) / "ggen-ci.toml"
            source = MANIFEST.read_text(encoding="utf-8")
            mutated.write_text(
                source.replace('workflow_name = "ggen CI"', 'workflow_name = "ggen CI falsifier"', 1),
                encoding="utf-8",
            )
            mutation = render(mutated)
            checks.append(
                check(
                    "negative manifest falsifier changes projection",
                    mutation != first,
                    mutation_sha256=digest(mutation),
                )
            )

        text = committed.decode("utf-8")
        generated_header = text.startswith("# @generated by tools/ggen_ci.py")
        checks.append(check("generated ownership header", generated_header))
        checks.append(check("legacy duplicate workflow absent", not LEGACY_WORKFLOW.exists()))

        action_refs = re.findall(r"uses:\s+[^@\s]+@([^\s]+)", text)
        immutable = bool(action_refs) and all(re.fullmatch(r"[0-9a-f]{40}", ref) for ref in action_refs)
        checks.append(check("external actions pinned to immutable SHA", immutable, refs=action_refs))
    except Exception as exc:  # verifier must emit a machine-readable refusal
        errors.append(str(exc))

    passed = not errors and all(bool(item["passed"]) for item in checks)
    report = {
        "schema": "chatmangpt.ggen-ci-verifier/v1",
        "manifest": str(MANIFEST.relative_to(ROOT)),
        "generator": str(RENDERER.relative_to(ROOT)),
        "artifact": str(WORKFLOW.relative_to(ROOT)),
        "checks": checks,
        "errors": errors,
        "bounded_standing": "ALIVE" if passed else "BUILD_BROKEN",
    }

    encoded = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if args.output:
        output = args.output if args.output.is_absolute() else ROOT / args.output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(encoded, encoding="utf-8")
    sys.stdout.write(encoded)
    return 0 if passed else 2


if __name__ == "__main__":
    raise SystemExit(main())
