// ============================================================
// DO NOT EDIT THIS FILE
//
// This file is auto-generated by ggen from:
//   ontology/zoela/autoreceipt.ttl
//
// Regenerate with: ggen sync
// ============================================================

//! Typestates for AutoReceiptPipeline — generated from ontology/zoela/autoreceipt.ttl
/// State: ArchitecturalReceiptParsed
#[derive(Debug, Clone, Copy)]
pub struct ArchitecturalReceiptParsed;
/// State: ExpectedOcelManufactured
#[derive(Debug, Clone, Copy)]
pub struct ExpectedOcelManufactured;
/// State: ExecutionRegistryBound
#[derive(Debug, Clone, Copy)]
pub struct ExecutionRegistryBound;
/// State: ObservedOcelCaptured
#[derive(Debug, Clone, Copy)]
pub struct ObservedOcelCaptured;
/// State: AlignmentVerified
#[derive(Debug, Clone, Copy)]
pub struct AlignmentVerified;
/// State: ReceiptEmitted
#[derive(Debug, Clone, Copy)]
pub struct ReceiptEmitted;

/// The AutoReceiptPipeline state machine.
#[derive(Debug, Clone, Copy)]
pub struct AutoReceiptPipeline<S> {
    #[allow(dead_code)]
    state: S,
}

impl AutoReceiptPipeline<ArchitecturalReceiptParsed> {
    /// Initialize the state machine in the starting state.
    pub fn new() -> Self {
        Self { state: ArchitecturalReceiptParsed }
    }
}

impl AutoReceiptPipeline<ArchitecturalReceiptParsed> {
    /// Transition from ArchitecturalReceiptParsed to ExpectedOcelManufactured.
    pub fn transition(self) -> AutoReceiptPipeline<ExpectedOcelManufactured> {
        AutoReceiptPipeline { state: ExpectedOcelManufactured }
    }
}
impl AutoReceiptPipeline<ExpectedOcelManufactured> {
    /// Transition from ExpectedOcelManufactured to ExecutionRegistryBound.
    pub fn transition(self) -> AutoReceiptPipeline<ExecutionRegistryBound> {
        AutoReceiptPipeline { state: ExecutionRegistryBound }
    }
}
impl AutoReceiptPipeline<ExecutionRegistryBound> {
    /// Transition from ExecutionRegistryBound to ObservedOcelCaptured.
    pub fn transition(self) -> AutoReceiptPipeline<ObservedOcelCaptured> {
        AutoReceiptPipeline { state: ObservedOcelCaptured }
    }
}
impl AutoReceiptPipeline<ObservedOcelCaptured> {
    /// Transition from ObservedOcelCaptured to AlignmentVerified.
    pub fn transition(self) -> AutoReceiptPipeline<AlignmentVerified> {
        AutoReceiptPipeline { state: AlignmentVerified }
    }
}
impl AutoReceiptPipeline<AlignmentVerified> {
    /// Transition from AlignmentVerified to ReceiptEmitted.
    pub fn transition(self) -> AutoReceiptPipeline<ReceiptEmitted> {
        AutoReceiptPipeline { state: ReceiptEmitted }
    }
}


