// ============================================================
// DO NOT EDIT THIS FILE
//
// This file is auto-generated by ggen from:
//   ontology/wasm4pm-stubs.ttl
//   ggen.toml: wasm4pm-stub rule
//
// Regenerate with: ggen sync
// ============================================================

//! WASM4PM type definitions and domain models
//!
//! Generated by ggen from ontology/wasm4pm-stubs.ttl
//! Do not edit — regenerate with: ggen sync
//!
//! Core data structures for process mining, conformance checking,
//! OCEL object-centric event logs, and POWL Petri net variants.

/// POWL (Partially Ordered Workflow Language) variant descriptor
/// Represents process structure with branching, concurrency, loops
#[derive(Debug, Clone)]
pub struct PowlVariant {
    pub id: String,
    pub label: String,
    pub activities: Vec<String>,
    pub edges: Vec<(String, String)>,  // (from_activity, to_activity)
}

/// POWL conformance result: fitness + precision metrics
/// Fitness: how well the log fits the model
/// Precision: how specific the model is to the log
#[derive(Debug, Clone)]
pub struct PowlConformance {
    pub variant_id: String,
    pub fitness: f64,
    pub precision: f64,
    pub generalization: f64,
    pub simplicity: f64,
}

/// OCEL event (Object-Centric Event Log)
/// Events describe process steps that manipulate multiple objects
#[derive(Debug, Clone)]
pub struct OcelEvent {
    pub id: String,
    pub activity: String,
    pub timestamp: String,
    pub objects: Vec<String>,  // List of object IDs involved
    pub attributes: std::collections::HashMap<String, String>,
}

/// OCEL object: an entity tracked through the process
/// Examples: order, invoice, shipment, customer
#[derive(Debug, Clone)]
pub struct OcelObject {
    pub id: String,
    pub object_type: String,
    pub attributes: std::collections::HashMap<String, String>,
}

/// OCEL object type: class of objects in the log
/// Examples: "Order", "Invoice", "Shipment", "Customer"
#[derive(Debug, Clone)]
pub struct OcelType {
    pub name: String,
    pub description: String,
    pub attributes: Vec<String>,
}

/// Event log: collection of traces
#[derive(Debug, Clone)]
pub struct EventLog {
    pub id: String,
    pub traces: Vec<Trace>,
    pub objects: Vec<OcelObject>,
}

/// Trace: ordered sequence of events
#[derive(Debug, Clone)]
pub struct Trace {
    pub id: String,
    pub events: Vec<Event>,
}

/// Event: minimal unit of process execution
#[derive(Debug, Clone)]
pub struct Event {
    pub id: String,
    pub activity: String,
    pub timestamp: String,
}
