// ============================================================
// DO NOT EDIT THIS FILE
//
// This file is auto-generated by ggen from:
//   ontology/wasm4pm-stubs.ttl
//   ggen.toml: wasm4pm-types-stub rule
//
// Regenerate with: ggen sync
// ============================================================

//! WASM4PM complete type system
//!
//! Generated by ggen from ontology/wasm4pm-stubs.ttl
//! Do not edit — regenerate with: ggen sync
//!
//! Unified type definitions for process mining, OCEL, and cognition-based synthesis.

// ============================================================================
// EVENT LOG TYPES
// ============================================================================

/// Event: atomic unit of observable behavior
#[derive(Debug, Clone)]
pub struct Event {
    pub id: String,
    pub activity: String,
    pub timestamp: String,
    pub resource: Option<String>,
}

/// Trace: ordered sequence of events forming a process instance
#[derive(Debug, Clone)]
pub struct Trace {
    pub id: String,
    pub events: Vec<Event>,
}

/// EventLog: collection of traces
#[derive(Debug, Clone)]
pub struct EventLog {
    pub id: String,
    pub traces: Vec<Trace>,
    pub metadata: std::collections::HashMap<String, String>,
}

// ============================================================================
// OBJECT-CENTRIC EVENT LOG (OCEL) TYPES
// ============================================================================

/// OcelEvent: event in object-centric context
#[derive(Debug, Clone)]
pub struct OcelEvent {
    pub id: String,
    pub activity: String,
    pub timestamp: String,
    pub objects: Vec<String>,  // Object IDs involved in this event
}

/// OcelObject: entity tracked through the process
#[derive(Debug, Clone)]
pub struct OcelObject {
    pub id: String,
    pub object_type: String,
    pub attributes: std::collections::HashMap<String, OcelAttributeValue>,
}

/// OcelType: class descriptor for objects
#[derive(Debug, Clone)]
pub struct OcelType {
    pub name: String,
    pub description: Option<String>,
    pub properties: Vec<String>,
}

/// OcelEventAttribute: attribute attached to an OCEL event
#[derive(Debug, Clone)]
pub struct OcelEventAttribute {
    pub name: String,
    pub value: OcelAttributeValue,
}

/// OcelAttributeValue: typed attribute value in OCEL
#[derive(Debug, Clone)]
pub enum OcelAttributeValue {
    String(String),
    Integer(i64),
    Float(f64),
    Boolean(bool),
    Timestamp(String),
}

// ============================================================================
// BREED (COGNITION) INPUT/OUTPUT TYPES
// ============================================================================

/// BreedInput: request structure for cognition oracles (ELIZA, CBR, etc.)
#[derive(Debug, Clone)]
pub struct BreedInput {
    pub oracle: String,  // e.g., "breed_eliza", "breed_cbr"
    pub query: String,
    pub context: std::collections::HashMap<String, String>,
}

/// BreedOutput: response from cognition oracle
#[derive(Debug, Clone)]
pub struct BreedOutput {
    pub oracle: String,
    pub solution: String,
    pub confidence: f64,
    pub reasoning: Option<String>,
}
