
//! Process mining event and trace types for wasm4pm
//!
//! Generated by ggen from ontology/pm4py-ocel-types.ttl
//! Do not edit — regenerate with: ggen sync
//!
//! Architecture:
//!   Tier 1  — ontology/pm4py-ocel-types.ttl   (source of truth)
//!   Tier 2  — ggen sync                       (manufacturing step)
//!   Tier 3  — src/types/pm4py/generated.rs    (this file, wired to lib)

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use chrono::{DateTime, Utc};

// ============================================================================
// LIFECYCLE STATES
// ============================================================================

/// Lifecycle states for events in the OCEL model.
/// Tracks the progression of an event through manufacturing stages.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LifecycleState {
    /// Created state
    CREATED,
    /// Inprogress state
    INPROGRESS,
    /// Completed state
    COMPLETED,
    /// Cancelled state
    CANCELLED,
    /// Active state
    ACTIVE,
    /// Inactive state
    INACTIVE,
    /// Seeded state
    SEEDED,
    /// Archived state
    ARCHIVED,
}

impl LifecycleState {
    /// Convert from string representation
    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "created" => Some(Self::CREATED),
            "inprogress" => Some(Self::INPROGRESS),
            "completed" => Some(Self::COMPLETED),
            "cancelled" => Some(Self::CANCELLED),
            "active" => Some(Self::ACTIVE),
            "inactive" => Some(Self::INACTIVE),
            "seeded" => Some(Self::SEEDED),
            "archived" => Some(Self::ARCHIVED),
            _ => None,
        }
    }

    /// Convert to string representation
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::CREATED => "created",
            Self::INPROGRESS => "inprogress",
            Self::COMPLETED => "completed",
            Self::CANCELLED => "cancelled",
            Self::ACTIVE => "active",
            Self::INACTIVE => "inactive",
            Self::SEEDED => "seeded",
            Self::ARCHIVED => "archived",
        }
    }
}

impl std::fmt::Display for LifecycleState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// ============================================================================
// STATE TRANSITIONS
// ============================================================================

/// Valid state transitions in the process mining lifecycle.
/// Defines which states can follow which other states.
pub struct StateTransitions;

impl StateTransitions {
    /// Check if transition from `from_state` to `to_state` is valid.
    pub fn is_valid(from_state: LifecycleState, to_state: LifecycleState) -> bool {
        matches!(
            (from_state, to_state),
            (LifecycleState::Created, LifecycleState::InProgress) |
            (LifecycleState::InProgress, LifecycleState::Completed) |
            (LifecycleState::InProgress, LifecycleState::Cancelled) |
            (LifecycleState::Completed, LifecycleState::Archived) |
            _ => false,
        )
    }

    /// Get all valid next states from the given state.
    pub fn valid_next_states(from_state: LifecycleState) -> Vec<LifecycleState> {
        let mut next = Vec::new();
        for candidate in &[
            LifecycleState::CREATED,
            LifecycleState::INPROGRESS,
            LifecycleState::COMPLETED,
            LifecycleState::CANCELLED,
            LifecycleState::ACTIVE,
            LifecycleState::INACTIVE,
            LifecycleState::SEEDED,
            LifecycleState::ARCHIVED,
        ] {
            if Self::is_valid(from_state, *candidate) {
                next.push(*candidate);
            }
        }
        next
    }
}

// ============================================================================
// ATTRIBUTE TYPE
// ============================================================================

/// An event attribute with key, value, and nested attributes.
/// Attributes can be primitive values or objects containing further attributes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Attribute {
    /// Attribute key (name)
    pub key: String,
    /// Attribute value
    pub value: String,
    /// Nested attributes (e.g. for object-valued attributes)
    #[serde(default)]
    pub own_attributes: HashMap<String, Attribute>,
}

impl Attribute {
    /// Create a new attribute with the given key and value.
    pub fn new(key: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            value: value.into(),
            own_attributes: HashMap::new(),
        }
    }

    /// Add a nested attribute to this attribute.
    pub fn with_attribute(mut self, attr: Attribute) -> Self {
        self.own_attributes.insert(attr.key.clone(), attr);
        self
    }

    /// Get a nested attribute by key.
    pub fn get_attribute(&self, key: &str) -> Option<&Attribute> {
        self.own_attributes.get(key)
    }

    /// Check if this attribute has any nested attributes.
    pub fn has_attributes(&self) -> bool {
        !self.own_attributes.is_empty()
    }
}

impl std::fmt::Display for Attribute {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}={}", self.key, self.value)
    }
}

// ============================================================================
// EVENT TYPE
// ============================================================================

/// An OCEL event — the atomic unit in an object-centric event log.
/// Events have identities, names, lifecycle states, timestamps, and attributes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    /// Unique event identifier
    pub id: String,
    /// Event name (activity/step label)
    pub name: String,
    /// Lifecycle state of this event
    pub lifecycle: LifecycleState,
    /// Timestamp when the event occurred
    pub timestamp: DateTime<Utc>,
    /// Event attributes (key-value pairs with nested structure)
    #[serde(default)]
    pub attributes: HashMap<String, Attribute>,
    /// Object references (which objects this event touches)
    #[serde(default)]
    pub object_refs: Vec<String>,
}

impl Event {
    /// Create a new event with the given id, name, lifecycle state, and timestamp.
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        lifecycle: LifecycleState,
        timestamp: DateTime<Utc>,
    ) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            lifecycle,
            timestamp,
            attributes: HashMap::new(),
            object_refs: Vec::new(),
        }
    }

    /// Add an attribute to this event.
    pub fn with_attribute(mut self, attr: Attribute) -> Self {
        self.attributes.insert(attr.key.clone(), attr);
        self
    }

    /// Get an attribute by key.
    pub fn get_attribute(&self, key: &str) -> Option<&Attribute> {
        self.attributes.get(key)
    }

    /// Add an object reference to this event.
    pub fn with_object_ref(mut self, obj_id: impl Into<String>) -> Self {
        self.object_refs.push(obj_id.into());
        self
    }

    /// Get all object references for this event.
    pub fn object_refs(&self) -> &[String] {
        &self.object_refs
    }

    /// Check if this event references a specific object.
    pub fn references_object(&self, obj_id: &str) -> bool {
        self.object_refs.iter().any(|ref_id| ref_id == obj_id)
    }

    /// Transition this event to a new lifecycle state (if valid).
    pub fn transition_to(&mut self, new_state: LifecycleState) -> Result<(), String> {
        if StateTransitions::is_valid(self.lifecycle, new_state) {
            self.lifecycle = new_state;
            Ok(())
        } else {
            Err(format!(
                "Invalid transition from {} to {}",
                self.lifecycle.as_str(),
                new_state.as_str()
            ))
        }
    }

    /// Get the number of attributes on this event.
    pub fn attribute_count(&self) -> usize {
        self.attributes.len()
    }

    /// Check if this event has any attributes.
    pub fn has_attributes(&self) -> bool {
        !self.attributes.is_empty()
    }
}

// ============================================================================
// TRACE TYPE
// ============================================================================

/// A trace is a sequence of events for a specific case (artifact instance).
/// Traces are the basic unit of conformance analysis in process mining.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trace {
    /// Unique case identifier
    pub case_id: String,
    /// Ordered sequence of events in this case
    #[serde(default)]
    pub events: Vec<Event>,
    /// Places (subprocesses/stages) touched by this trace
    #[serde(default)]
    pub places: Vec<String>,
}

impl Trace {
    /// Create a new trace with the given case id.
    pub fn new(case_id: impl Into<String>) -> Self {
        Self {
            case_id: case_id.into(),
            events: Vec::new(),
            places: Vec::new(),
        }
    }

    /// Add an event to this trace (appends to end of sequence).
    pub fn with_event(mut self, event: Event) -> Self {
        self.events.push(event);
        self
    }

    /// Add multiple events to this trace at once.
    pub fn with_events(mut self, events: Vec<Event>) -> Self {
        self.events.extend(events);
        self
    }

    /// Get the event at the specified index (0-based).
    pub fn get_event(&self, index: usize) -> Option<&Event> {
        self.events.get(index)
    }

    /// Get all events in this trace.
    pub fn events(&self) -> &[Event] {
        &self.events
    }

    /// Get the number of events in this trace.
    pub fn event_count(&self) -> usize {
        self.events.len()
    }

    /// Get the first event in this trace (if any).
    pub fn first_event(&self) -> Option<&Event> {
        self.events.first()
    }

    /// Get the last event in this trace (if any).
    pub fn last_event(&self) -> Option<&Event> {
        self.events.last()
    }

    /// Check if this trace is empty (no events).
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Add a place (subprocess/stage) to this trace.
    pub fn with_place(mut self, place: impl Into<String>) -> Self {
        self.places.push(place.into());
        self
    }

    /// Get all places touched by this trace.
    pub fn places(&self) -> &[String] {
        &self.places
    }

    /// Get the number of places touched by this trace.
    pub fn place_count(&self) -> usize {
        self.places.len()
    }

    /// Check if this trace touched a specific place.
    pub fn visited_place(&self, place: &str) -> bool {
        self.places.iter().any(|p| p == place)
    }

    /// Get the trace as a sequence of event names.
    pub fn event_sequence(&self) -> Vec<&str> {
        self.events.iter().map(|e| e.name.as_str()).collect()
    }

    /// Get the trace as a sequence of lifecycle states.
    pub fn lifecycle_sequence(&self) -> Vec<LifecycleState> {
        self.events.iter().map(|e| e.lifecycle).collect()
    }
}

// ============================================================================
// EVENT LOG TYPE
// ============================================================================

/// An OCEL (Object-Centric Event Log) — collection of traces for process mining.
/// Event logs are validated against process models using conformance checking.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventLog {
    /// Collection of traces in this event log
    #[serde(default)]
    pub traces: Vec<Trace>,
}

impl EventLog {
    /// Create a new empty event log.
    pub fn new() -> Self {
        Self {
            traces: Vec::new(),
        }
    }

    /// Create an event log from the default context (empty).
    pub fn from_default() -> Self {
        Self::new()
    }

    /// Add a trace to this event log.
    pub fn with_trace(mut self, trace: Trace) -> Self {
        self.traces.push(trace);
        self
    }

    /// Add multiple traces to this event log.
    pub fn with_traces(mut self, traces: Vec<Trace>) -> Self {
        self.traces.extend(traces);
        self
    }

    /// Get a trace by index.
    pub fn get_trace(&self, index: usize) -> Option<&Trace> {
        self.traces.get(index)
    }

    /// Get all traces in this event log.
    pub fn traces(&self) -> &[Trace] {
        &self.traces
    }

    /// Get the number of traces in this event log.
    pub fn trace_count(&self) -> usize {
        self.traces.len()
    }

    /// Get the total number of events across all traces.
    pub fn total_event_count(&self) -> usize {
        self.traces.iter().map(|t| t.event_count()).sum()
    }

    /// Check if this event log is empty (no traces).
    pub fn is_empty(&self) -> bool {
        self.traces.is_empty()
    }

    /// Get the trace with the specified case id (if any).
    pub fn get_trace_by_case_id(&self, case_id: &str) -> Option<&Trace> {
        self.traces.iter().find(|t| t.case_id == case_id)
    }

    /// Get all unique event names across all traces.
    pub fn all_event_names(&self) -> Vec<&str> {
        let mut names = Vec::new();
        for trace in &self.traces {
            for event in &trace.events {
                if !names.contains(&event.name.as_str()) {
                    names.push(event.name.as_str());
                }
            }
        }
        names
    }

    /// Get all unique places across all traces.
    pub fn all_places(&self) -> Vec<&str> {
        let mut places = Vec::new();
        for trace in &self.traces {
            for place in &trace.places {
                if !places.contains(&place.as_str()) {
                    places.push(place.as_str());
                }
            }
        }
        places
    }

    /// Get statistics about this event log.
    pub fn statistics(&self) -> LogStatistics {
        LogStatistics {
            trace_count: self.trace_count(),
            event_count: self.total_event_count(),
            unique_activities: self.all_event_names().len(),
            unique_places: self.all_places().len(),
            min_trace_length: self.traces.iter().map(|t| t.event_count()).min().unwrap_or(0),
            max_trace_length: self.traces.iter().map(|t| t.event_count()).max().unwrap_or(0),
        }
    }
}

impl Default for EventLog {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// STATISTICS
// ============================================================================

/// Statistics summarizing an event log.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogStatistics {
    /// Total number of traces in the log
    pub trace_count: usize,
    /// Total number of events across all traces
    pub event_count: usize,
    /// Number of unique activity names
    pub unique_activities: usize,
    /// Number of unique places/stages
    pub unique_places: usize,
    /// Shortest trace length
    pub min_trace_length: usize,
    /// Longest trace length
    pub max_trace_length: usize,
}

impl LogStatistics {
    /// Get average trace length.
    pub fn average_trace_length(&self) -> f64 {
        if self.trace_count == 0 {
            0.0
        } else {
            self.event_count as f64 / self.trace_count as f64
        }
    }
}

impl std::fmt::Display for LogStatistics {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "EventLog: {} traces, {} events, {} activities, {} places (trace length: {}-{})",
            self.trace_count,
            self.event_count,
            self.unique_activities,
            self.unique_places,
            self.min_trace_length,
            self.max_trace_length
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lifecycle_from_str() {
        assert_eq!(LifecycleState::from_str("created"), Some(LifecycleState::CREATED));
        assert_eq!(LifecycleState::from_str("unknown"), None);
    }

    #[test]
    fn test_attribute_creation() {
        let attr = Attribute::new("test_key", "test_value");
        assert_eq!(attr.key, "test_key");
        assert_eq!(attr.value, "test_value");
        assert!(!attr.has_attributes());
    }

    #[test]
    fn test_event_creation() {
        let now = Utc::now();
        let event = Event::new("evt1", "start", LifecycleState::SEEDED, now);
        assert_eq!(event.id, "evt1");
        assert_eq!(event.name, "start");
        assert_eq!(event.lifecycle, LifecycleState::SEEDED);
        assert!(!event.has_attributes());
    }

    #[test]
    fn test_trace_creation() {
        let trace = Trace::new("case1");
        assert_eq!(trace.case_id, "case1");
        assert!(trace.is_empty());
    }

    #[test]
    fn test_event_log_creation() {
        let log = EventLog::new();
        assert!(log.is_empty());
        assert_eq!(log.trace_count(), 0);
    }

    #[test]
    fn test_event_log_with_trace() {
        let trace = Trace::new("case1");
        let log = EventLog::new().with_trace(trace);
        assert_eq!(log.trace_count(), 1);
    }
}