
-- =============================================================================
-- ZOE LA Supabase Legacy-Coverage — generated from declarative profile
-- =============================================================================
-- DO NOT EDIT. Generated by ggen from:
--   ontology/profiles/zoela-legacy-coverage.ttl
-- Regenerate with: ggen sync --rule zoela-legacy-coverage
--
-- Holds every table + RLS not yet reachable from the public-vocab admission
-- chain (campuses, consent_records, group_interests, group_memberships,
-- group_invites, ocel_events) plus extra columns for partially-admitted
-- tables (persons, connect_groups).
-- =============================================================================

-- ----------------------------------------------------------------------------
-- § 1  Tables
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS campuses (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  name            TEXT        NOT NULL,
  slug            TEXT        NOT NULL UNIQUE,
  campus_code     TEXT,
  campus_city     TEXT,
  location_mode   TEXT        NOT NULL DEFAULT 'in-person',
  campus_timezone TEXT        DEFAULT 'America/Los_Angeles',
  is_active       BOOLEAN     NOT NULL DEFAULT true
);

ALTER TABLE campuses ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_campuses_updated_at ON campuses;
CREATE TRIGGER set_campuses_updated_at
  BEFORE UPDATE ON campuses
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS consent_records (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  person_id           UUID        NOT NULL REFERENCES persons(id),
  consent_type        TEXT        NOT NULL,
  granted             BOOLEAN     NOT NULL DEFAULT false,
  granted_at          TIMESTAMPTZ,
  revoked_at          TIMESTAMPTZ,
  granted_by          TEXT,
  is_guardian_consent BOOLEAN     DEFAULT false
);

ALTER TABLE consent_records ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_consent_records_updated_at ON consent_records;
CREATE TRIGGER set_consent_records_updated_at
  BEFORE UPDATE ON consent_records
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS group_interests (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  person_id           UUID        NOT NULL REFERENCES persons(id),
  campus_id           UUID        REFERENCES campuses(id),
  schedule_preference TEXT,
  location_preference TEXT        DEFAULT 'in-person',
  submitted_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  matched_group_id    UUID        REFERENCES connect_groups(id),
  match_status        TEXT        NOT NULL DEFAULT 'pending'
);

ALTER TABLE group_interests ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_group_interests_updated_at ON group_interests;
CREATE TRIGGER set_group_interests_updated_at
  BEFORE UPDATE ON group_interests
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS group_memberships (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  person_id   UUID        NOT NULL REFERENCES persons(id),
  group_id    UUID        NOT NULL REFERENCES connect_groups(id),
  member_role TEXT        NOT NULL DEFAULT 'member',
  joined_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_active   BOOLEAN     NOT NULL DEFAULT true,
  UNIQUE (person_id, group_id)
);

ALTER TABLE group_memberships ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_group_memberships_updated_at ON group_memberships;
CREATE TRIGGER set_group_memberships_updated_at
  BEFORE UPDATE ON group_memberships
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS group_invites (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  person_id    UUID        NOT NULL REFERENCES persons(id),
  group_id     UUID        NOT NULL REFERENCES connect_groups(id),
  invited_by   UUID        REFERENCES persons(id),
  status       TEXT        NOT NULL DEFAULT 'pending',
  sent_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  responded_at TIMESTAMPTZ,
  UNIQUE (person_id, group_id)
);

ALTER TABLE group_invites ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_group_invites_updated_at ON group_invites;
CREATE TRIGGER set_group_invites_updated_at
  BEFORE UPDATE ON group_invites
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS ocel_events (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  event_type   TEXT        NOT NULL,
  object_id    TEXT        NOT NULL,
  object_type  TEXT        NOT NULL,
  route_id     TEXT        NOT NULL,
  stage_code   TEXT        NOT NULL,
  action_class TEXT        NOT NULL,
  run_id       UUID        NOT NULL,
  ts_ns        BIGINT      NOT NULL,
  fields       JSONB       DEFAULT '{}'::jsonb,
  receipt_hash TEXT
);

ALTER TABLE ocel_events ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_ocel_events_updated_at ON ocel_events;
CREATE TRIGGER set_ocel_events_updated_at
  BEFORE UPDATE ON ocel_events
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX IF NOT EXISTS idx_ocel_events_run_id    ON ocel_events(run_id);
CREATE INDEX IF NOT EXISTS idx_ocel_events_route_id  ON ocel_events(route_id);
CREATE INDEX IF NOT EXISTS idx_ocel_events_object_id ON ocel_events(object_id);

-- ----------------------------------------------------------------------------
-- § 2  Alters (extra columns on partially-admitted tables)
-- ----------------------------------------------------------------------------

-- ALTER persons
ALTER TABLE persons ADD COLUMN IF NOT EXISTS full_name   TEXT;
ALTER TABLE persons ADD COLUMN IF NOT EXISTS campus_id   UUID REFERENCES campuses(id);

-- ALTER connect_groups
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS name            TEXT;
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS campus_id       UUID REFERENCES campuses(id);
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS leader_id       UUID REFERENCES persons(id);
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS host_id         UUID REFERENCES persons(id);
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS group_code      TEXT;
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS max_capacity    INTEGER     NOT NULL DEFAULT 12;
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS current_count   INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS is_private      BOOLEAN     NOT NULL DEFAULT false;
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS location_mode   TEXT        NOT NULL DEFAULT 'in-person';
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS meeting_day     TEXT;
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS meeting_time    TEXT;
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS group_frequency TEXT        DEFAULT 'weekly';
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS is_open         BOOLEAN     NOT NULL DEFAULT true;

-- ----------------------------------------------------------------------------
-- § 3  Policies (legacy RLS not yet driven by the ODRL chain)
-- ----------------------------------------------------------------------------

DROP POLICY IF EXISTS "auth_read__select__campuses" ON campuses;
CREATE POLICY "auth_read__select__campuses"
  ON campuses
  FOR SELECT
  TO authenticated
  USING (true)
  ;

DROP POLICY IF EXISTS "leader_update__update__connect_groups" ON connect_groups;
CREATE POLICY "leader_update__update__connect_groups"
  ON connect_groups
  FOR UPDATE
  TO authenticated
  USING (leader_id = auth.uid() OR host_id = auth.uid())
  WITH CHECK (true)
  ;

DROP POLICY IF EXISTS "person_read_own__select__consent_records" ON consent_records;
CREATE POLICY "person_read_own__select__consent_records"
  ON consent_records
  FOR SELECT
  TO authenticated
  USING (person_id = auth.uid())
  ;

DROP POLICY IF EXISTS "person_insert_own__insert__consent_records" ON consent_records;
CREATE POLICY "person_insert_own__insert__consent_records"
  ON consent_records
  FOR INSERT
  TO authenticated
  WITH CHECK (person_id = auth.uid())
  ;

DROP POLICY IF EXISTS "person_or_leader_read__select__group_interests" ON group_interests;
CREATE POLICY "person_or_leader_read__select__group_interests"
  ON group_interests
  FOR SELECT
  TO authenticated
  USING (person_id = auth.uid() OR EXISTS (SELECT 1 FROM connect_groups cg WHERE cg.leader_id = auth.uid()))
  ;

DROP POLICY IF EXISTS "auth_insert__insert__group_interests" ON group_interests;
CREATE POLICY "auth_insert__insert__group_interests"
  ON group_interests
  FOR INSERT
  TO authenticated
  WITH CHECK (true)
  ;

DROP POLICY IF EXISTS "auth_read__select__group_memberships" ON group_memberships;
CREATE POLICY "auth_read__select__group_memberships"
  ON group_memberships
  FOR SELECT
  TO authenticated
  USING (true)
  ;

DROP POLICY IF EXISTS "auth_insert__insert__group_memberships" ON group_memberships;
CREATE POLICY "auth_insert__insert__group_memberships"
  ON group_memberships
  FOR INSERT
  TO authenticated
  WITH CHECK (true)
  ;

DROP POLICY IF EXISTS "auth_read__select__group_invites" ON group_invites;
CREATE POLICY "auth_read__select__group_invites"
  ON group_invites
  FOR SELECT
  TO authenticated
  USING (true)
  ;

DROP POLICY IF EXISTS "auth_insert__insert__group_invites" ON group_invites;
CREATE POLICY "auth_insert__insert__group_invites"
  ON group_invites
  FOR INSERT
  TO authenticated
  WITH CHECK (true)
  ;

DROP POLICY IF EXISTS "auth_read__select__ocel_events" ON ocel_events;
CREATE POLICY "auth_read__select__ocel_events"
  ON ocel_events
  FOR SELECT
  TO authenticated
  USING (true)
  ;

-- =============================================================================
-- End of legacy coverage.
-- =============================================================================
