
-- =============================================================================
-- ZOE LA Supabase Migration — generated from admissibility-gated extraction
-- =============================================================================
-- DO NOT EDIT. Generated by ggen from:
--   ontology/zoela/*.ttl                                    (church-service domain)
--   ontology/profiles/zoela-supabase-materialization.ttl    (kinds + priorities)
--   ontology/profiles/public-role-shapes.ttl                (SHACL contracts)
--   ontology/profiles/zoela-supabase-rls.ttl                (ODRL → RLS mapping)
-- Regenerate with: ggen sync --rule zoela-public-materialization
--
-- Doctrine: a table appears here only when ALL four admission conditions hold —
-- public-anchor specialization, SHACL shape, ODRL policy (if rlsRequired), and
-- ggen:emitsSql=true on the materialization kind with no priority ambiguity.
-- Refusals are audited in supabase-materialization-refusals.tera, not here.
-- See: memory/feedback_public_vocab_materialization.md
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;
-- ----------------------------------------------------------------------------
-- Admitted materializations: 4
-- (Every row below is admitted by construction. Refusals → supabase-materialization-refusals.sql)
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- Household (OrganizationMaterialization)
--   Local class:          https://zoela.org/ontology/Household
--   Public anchor:        https://schema.org/Organization
--   Materialization kind: https://open-ontologies.org/ggen#OrganizationMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#OrganizationMaterializationShape
--   A family or cohabiting group registered with ZOE LA, used to group PersonProfiles by physical address.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS households (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ
);

ALTER TABLE households ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_households_updated_at ON households;
CREATE TRIGGER set_households_updated_at
  BEFORE UPDATE ON households
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- ----------------------------------------------------------------------------
-- Push Notification (ActionMaterialization)
--   Local class:          https://zoela.org/ontology/PushNotification
--   Public anchor:        https://schema.org/Action
--   Materialization kind: https://open-ontologies.org/ggen#ActionMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#ActionMaterializationShape
--   A push notification dispatched to a PersonProfile's device when a RouteStage transition occurs. Carries a title, body, category, and deep-link route back into the app.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS push_notification (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ,
  created_by  UUID NOT NULL REFERENCES auth.users(id)
);

ALTER TABLE push_notification ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_push_notification_updated_at ON push_notification;
CREATE TRIGGER set_push_notification_updated_at
  BEFORE UPDATE ON push_notification
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- ----------------------------------------------------------------------------
-- Person Profile (AgentMaterialization)
--   Local class:          https://zoela.org/ontology/PersonProfile
--   Public anchor:        https://schema.org/Person
--   Materialization kind: https://open-ontologies.org/ggen#AgentMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#AgentMaterializationShape
--   A church member or visitor whose identity and household affiliation are tracked in the ZOE LA Mobile app.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS persons (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ
);

ALTER TABLE persons ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_persons_updated_at ON persons;
CREATE TRIGGER set_persons_updated_at
  BEFORE UPDATE ON persons
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- ----------------------------------------------------------------------------
-- Connect Group (OrganizationMaterialization)
--   Local class:          https://zoela.org/ontology/ConnectGroup
--   Public anchor:        http://www.w3.org/ns/org#OrganizationalUnit
--   Materialization kind: https://open-ontologies.org/ggen#OrganizationMaterialization
--   SHACL shape:          https://open-ontologies.org/ggen#OrganizationMaterializationShape
--   A small-group community formation unit within ZOE LA. Functions as both a recurring gathering event and a formal organisational unit with defined membership and leadership.
-- ----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS connect_groups (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ
);

ALTER TABLE connect_groups ENABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS set_connect_groups_updated_at ON connect_groups;
CREATE TRIGGER set_connect_groups_updated_at
  BEFORE UPDATE ON connect_groups
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (RLS policies for this table are emitted by supabase-rls.tera consuming
--  extract-odrl-policies.rq. Without a policy, the table is locked.)

-- =============================================================================
-- End of generated migration. Every table above passed all admissibility gates.
-- Refused candidates appear in supabase-materialization-refusals.sql, not here.
-- =============================================================================
