
-- =============================================================================
-- ZOE LA Supabase Body Columns — generated from admissibility-gated extraction
-- =============================================================================
-- DO NOT EDIT. Generated by ggen from:
--   .specify/queries/zoela/extract-public-materialization-columns.rq
--
-- Doctrine: one ALTER TABLE ADD COLUMN per admitted (class, property) tuple.
-- Tables themselves come from zoela-tables.sql; this file adds body columns.
-- Run AFTER zoela-tables.sql.
-- =============================================================================

-- ----------------------------------------------------------------------------
-- Body column rows: 24
-- ----------------------------------------------------------------------------
-- Full body text of the push notification providing context and call-to-action. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS notification_body TEXT;
-- The generation segment this Connect Group is designed to serve. Drawn from the GenerationSegmentScheme vocabulary. (from https://zoela.org/ontology/ConnectGroup)
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS group_target_generation UUID;
-- Links a PushNotification to the PersonProfile whose device receives the notification. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS sent_to_person UUID REFERENCES persons(id);
-- Maximum number of members the group can accommodate. Used to determine open/closed status. (from https://zoela.org/ontology/ConnectGroup)
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS max_capacity INTEGER;
-- City in which the household is located. (from https://zoela.org/ontology/Household)
ALTER TABLE households ADD COLUMN IF NOT EXISTS city TEXT;
-- Given (first) name of the person. (from https://zoela.org/ontology/PersonProfile)
ALTER TABLE persons ADD COLUMN IF NOT EXISTS first_name TEXT;
-- Family (last) name of the person. (from https://zoela.org/ontology/PersonProfile)
ALTER TABLE persons ADD COLUMN IF NOT EXISTS last_name TEXT;
-- Short alphanumeric code uniquely identifying the Connect Group within its campus (e.g. HLP-CG-01). Used as a routing key in the manufacturing pipeline. (from https://zoela.org/ontology/ConnectGroup)
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS group_code TEXT;
-- Display name for the household  typically the primary family surname. (from https://zoela.org/ontology/Household)
ALTER TABLE households ADD COLUMN IF NOT EXISTS household_name TEXT;
-- Primary phone number in E.164 format. (from https://zoela.org/ontology/PersonProfile)
ALTER TABLE persons ADD COLUMN IF NOT EXISTS phone TEXT;
-- Short headline text of the push notification  displayed in the device notification shade. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS notification_title TEXT;
-- Expo deep-link URI that opens the relevant screen in ZOE LA Mobile when the notification is tapped. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS deep_link_route TEXT;
-- US postal (ZIP) code for the household's address. (from https://zoela.org/ontology/Household)
ALTER TABLE households ADD COLUMN IF NOT EXISTS zip TEXT;
-- Links a PushNotification to the RouteStage whose completion or activation triggered the notification dispatch. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS triggered_by_stage UUID;
-- Membership role of the person within ZOE LA (e.g.  member  leader  visitor  staff). (from https://zoela.org/ontology/PersonProfile)
ALTER TABLE persons ADD COLUMN IF NOT EXISTS role TEXT;
-- Links a PersonProfile to the Household to which the person belongs. (from https://zoela.org/ontology/PersonProfile)
ALTER TABLE persons ADD COLUMN IF NOT EXISTS household_id UUID REFERENCES households(id);
-- Primary email address used for login and notifications. (from https://zoela.org/ontology/PersonProfile)
ALTER TABLE persons ADD COLUMN IF NOT EXISTS email TEXT;
-- Identifier of the person holding the primary leadership role for this Connect Group. (from https://zoela.org/ontology/ConnectGroup)
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS group_leader_id TEXT;
-- Recurrence cadence for group meetings. Allowed values  weekly  biweekly  monthly. (from https://zoela.org/ontology/ConnectGroup)
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS group_frequency TEXT;
-- First line of the household's street address. (from https://zoela.org/ontology/Household)
ALTER TABLE households ADD COLUMN IF NOT EXISTS address_line1 TEXT;
-- Category identifier from the NotificationCategoryScheme  used to route and filter notifications in the app. (from https://zoela.org/ontology/PushNotification)
ALTER TABLE push_notification ADD COLUMN IF NOT EXISTS notification_category TEXT;
-- Associates the Connect Group with the ZOE LA campus at which it primarily meets. (from https://zoela.org/ontology/ConnectGroup)
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS group_has_campus UUID;
-- True when the group is accepting new members (currentSize < maxCapacity and group is active). (from https://zoela.org/ontology/ConnectGroup)
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS is_open BOOLEAN;
-- Current number of active members in the group. Compared against maxCapacity to compute availability. (from https://zoela.org/ontology/ConnectGroup)
ALTER TABLE connect_groups ADD COLUMN IF NOT EXISTS current_size INTEGER;

-- =============================================================================
-- End of body column additions.
-- =============================================================================
