
// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/navigation.ttl + extract-navigation.rq
// Regenerate: ggen sync --rule zoela-navigation
// Tab: Serve (SERVE)

import { createNativeStackNavigator } from '@react-navigation/native-stack';
import React from 'react';

export type RootStackParamList = Record<string, { routeId?: string } | undefined>;

const SERVEStack = createNativeStackNavigator<RootStackParamList>();

export function SERVENavigator() {
  return (
    <SERVEStack.Navigator>
      {/* screen_id: volunteer_opportunities */}
      <SERVEStack.Screen name="VolunteerOpportunities" getComponent={() => require('./screens/VolunteerOpportunities').default} />
    </SERVEStack.Navigator>
  );
}
