
// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/navigation.ttl + extract-navigation.rq
// Regenerate: ggen sync --rule zoela-navigation

import { createNativeStackNavigator } from '@react-navigation/native-stack';
import React from 'react';

export type RootStackParamList = Record<string, { routeId?: string } | undefined>;

// Tab navigators: 7

// ----------------------------------------------------------------
// Tab: Admin (ADMIN)
// ----------------------------------------------------------------
const ADMINStack = createNativeStackNavigator<RootStackParamList>();

export function ADMINNavigator() {
  return (
    <ADMINStack.Navigator>
      {/* ADMIN ONLY · admin_followups_overdue */}
      <ADMINStack.Screen name="AdminFollowUpsOverdue" getComponent={() => require('./screens/AdminFollowUpsOverdue').default} />
      {/* ADMIN ONLY · admin_pending_receipts */}
      <ADMINStack.Screen name="AdminPendingReceipts" getComponent={() => require('./screens/AdminPendingReceipts').default} />
      {/* ADMIN ONLY · admin_open_needs */}
      <ADMINStack.Screen name="AdminOpenNeeds" getComponent={() => require('./screens/AdminOpenNeeds').default} />
    </ADMINStack.Navigator>
  );
}

// ----------------------------------------------------------------
// Tab: ZOE Cares (CARE)
// ----------------------------------------------------------------
const CAREStack = createNativeStackNavigator<RootStackParamList>();

export function CARENavigator() {
  return (
    <CAREStack.Navigator>
      {/* new_care_request */}
      <CAREStack.Screen name="NewCareRequest" getComponent={() => require('./screens/NewCareRequest').default} />
      {/* care_request_list */}
      <CAREStack.Screen name="CareRequestList" getComponent={() => require('./screens/CareRequestList').default} />
    </CAREStack.Navigator>
  );
}

// ----------------------------------------------------------------
// Tab: Events (EVENTS)
// ----------------------------------------------------------------
const EVENTSStack = createNativeStackNavigator<RootStackParamList>();

export function EVENTSNavigator() {
  return (
    <EVENTSStack.Navigator>
      {/* event_detail */}
      <EVENTSStack.Screen name="EventDetail" getComponent={() => require('./screens/EventDetail').default} />
      {/* event_list */}
      <EVENTSStack.Screen name="EventList" getComponent={() => require('./screens/EventList').default} />
    </EVENTSStack.Navigator>
  );
}

// ----------------------------------------------------------------
// Tab: Groups (GROUPS)
// ----------------------------------------------------------------
const GROUPSStack = createNativeStackNavigator<RootStackParamList>();

export function GROUPSNavigator() {
  return (
    <GROUPSStack.Navigator>
      {/* group_interest_form */}
      <GROUPSStack.Screen name="GroupInterestForm" getComponent={() => require('./screens/GroupInterestForm').default} />
      {/* my_groups */}
      <GROUPSStack.Screen name="MyGroups" getComponent={() => require('./screens/MyGroups').default} />
      {/* connect_group_detail */}
      <GROUPSStack.Screen name="ConnectGroupDetail" getComponent={() => require('./screens/ConnectGroupDetail').default} />
      {/* connect_groups_home */}
      <GROUPSStack.Screen name="ConnectGroupsHome" getComponent={() => require('./screens/ConnectGroupsHome').default} />
      {/* connect_group_list */}
      <GROUPSStack.Screen name="ConnectGroupList" getComponent={() => require('./screens/ConnectGroupList').default} />
    </GROUPSStack.Navigator>
  );
}

// ----------------------------------------------------------------
// Tab: Home (HOME)
// ----------------------------------------------------------------
const HOMEStack = createNativeStackNavigator<RootStackParamList>();

export function HOMENavigator() {
  return (
    <HOMEStack.Navigator>
      {/* home_feed */}
      <HOMEStack.Screen name="HomeFeed" getComponent={() => require('./screens/HomeFeed').default} />
    </HOMEStack.Navigator>
  );
}

// ----------------------------------------------------------------
// Tab: Profile (PROFILE)
// ----------------------------------------------------------------
const PROFILEStack = createNativeStackNavigator<RootStackParamList>();

export function PROFILENavigator() {
  return (
    <PROFILEStack.Navigator>
    </PROFILEStack.Navigator>
  );
}

// ----------------------------------------------------------------
// Tab: Serve (SERVE)
// ----------------------------------------------------------------
const SERVEStack = createNativeStackNavigator<RootStackParamList>();

export function SERVENavigator() {
  return (
    <SERVEStack.Navigator>
      {/* volunteer_opportunities */}
      <SERVEStack.Screen name="VolunteerOpportunities" getComponent={() => require('./screens/VolunteerOpportunities').default} />
    </SERVEStack.Navigator>
  );
}
