// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/connect-group-routes.ttl

import { RouteStage } from '../types/routes';











export const CG_ROUTE_STAGES: RouteStage[] = [

  {
    code: "cg-interest-expressed",
    label: "Interest Expressed",
    order: 1,
    isEntry: true,
    isTerminal: false,
    predecessorCode: "",
    ocelEventType: "connect_group.interest_expressed",
    autonomicActionClass: "A1",
    requiredGates: "".split("|").filter(Boolean),
  },

  {
    code: "cg-preferences-collected",
    label: "Preferences Collected",
    order: 2,
    isEntry: false,
    isTerminal: false,
    predecessorCode: "cg-interest-expressed",
    ocelEventType: "connect_group.preferences_collected",
    autonomicActionClass: "A1",
    requiredGates: "".split("|").filter(Boolean),
  },

  {
    code: "cg-eligible-groups-found",
    label: "Eligible Groups Found",
    order: 3,
    isEntry: false,
    isTerminal: false,
    predecessorCode: "cg-preferences-collected",
    ocelEventType: "connect_group.eligible_groups_found",
    autonomicActionClass: "A2",
    requiredGates: "CapacityGate".split("|").filter(Boolean),
  },

  {
    code: "cg-invite-sent",
    label: "Invite Sent",
    order: 4,
    isEntry: false,
    isTerminal: false,
    predecessorCode: "cg-eligible-groups-found",
    ocelEventType: "connect_group.invite_sent",
    autonomicActionClass: "A2",
    requiredGates: "ScheduleGate".split("|").filter(Boolean),
  },

  {
    code: "cg-invite-accepted",
    label: "Invite Accepted",
    order: 5,
    isEntry: false,
    isTerminal: false,
    predecessorCode: "cg-invite-sent",
    ocelEventType: "connect_group.invite_accepted",
    autonomicActionClass: "A1",
    requiredGates: "ConsentGate".split("|").filter(Boolean),
  },

  {
    code: "cg-first-meeting-attended",
    label: "First Meeting Attended",
    order: 6,
    isEntry: false,
    isTerminal: false,
    predecessorCode: "cg-invite-accepted",
    ocelEventType: "connect_group.first_meeting_attended",
    autonomicActionClass: "A1",
    requiredGates: "NotificationBudgetGate".split("|").filter(Boolean),
  },

  {
    code: "cg-followup-completed",
    label: "Follow-Up Completed",
    order: 7,
    isEntry: false,
    isTerminal: false,
    predecessorCode: "cg-first-meeting-attended",
    ocelEventType: "connect_group.followup_completed",
    autonomicActionClass: "A1",
    requiredGates: "CapacityGate".split("|").filter(Boolean),
  },

  {
    code: "cg-membership-active",
    label: "Membership Active",
    order: 8,
    isEntry: false,
    isTerminal: true,
    predecessorCode: "cg-followup-completed",
    ocelEventType: "connect_group.membership_active",
    autonomicActionClass: "A1",
    requiredGates: "".split("|").filter(Boolean),
  },

];

export const CG_STAGE_MAP = new Map(
  CG_ROUTE_STAGES.map(s => [s.code, s])
);

export function getNextStages(stageCode: string): RouteStage[] {
  return CG_ROUTE_STAGES.filter(s => s.predecessorCode === stageCode);
}
