// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/connect-group-routes.ttl

export type Urgency = 'low' | 'normal' | 'high';

export interface AdminSurface {
  code: string;
  label: string;
  description: string;
  filterStageCode: string;
  urgency: Urgency;
}







export const CG_ADMIN_SURFACES: AdminSurface[] = [

  {
    code: "open-interests",
    label: "Open Group Interests",
    description: "Interests submitted awaiting matching",
    filterStageCode: "cg-interest-expressed",
    urgency: "normal" as Urgency,
  },

  {
    code: "unmatched-people",
    label: "Unmatched People",
    description: "No eligible groups found for expressed interests",
    filterStageCode: "cg-eligible-groups-found",
    urgency: "high" as Urgency,
  },

  {
    code: "invites-not-accepted",
    label: "Invites Sent / Not Accepted",
    description: "Invites sent with no response within 7 days",
    filterStageCode: "cg-invite-sent",
    urgency: "normal" as Urgency,
  },

  {
    code: "first-meeting-missed",
    label: "First Meeting Missed",
    description: "Accepted invite but did not attend first meeting",
    filterStageCode: "cg-invite-accepted",
    urgency: "high" as Urgency,
  },

  {
    code: "followups-overdue",
    label: "Follow-Ups Overdue",
    description: "Follow-ups not completed within expected window",
    filterStageCode: "cg-followup-completed",
    urgency: "high" as Urgency,
  },

  {
    code: "near-capacity",
    label: "Groups Near Capacity",
    description: "Groups at 80% or more capacity",
    filterStageCode: "",
    urgency: "normal" as Urgency,
  },

  {
    code: "under-capacity",
    label: "Groups Under Capacity",
    description: "Groups below minimum capacity threshold",
    filterStageCode: "",
    urgency: "low" as Urgency,
  },

  {
    code: "without-leader",
    label: "Groups Without Leader",
    description: "Active groups with no assigned leader",
    filterStageCode: "",
    urgency: "high" as Urgency,
  },

  {
    code: "private-approval",
    label: "Private Approval Required",
    description: "Interests requiring manual leader approval",
    filterStageCode: "cg-eligible-groups-found",
    urgency: "high" as Urgency,
  },

  {
    code: "route-refusals",
    label: "Route Refusals",
    description: "Consent or policy refusals emitted by the system",
    filterStageCode: "",
    urgency: "normal" as Urgency,
  },

  {
    code: "autonomic-matched",
    label: "Autonomically Matched Today",
    description: "Matches completed autonomically in last 24h",
    filterStageCode: "cg-membership-active",
    urgency: "normal" as Urgency,
  },

  {
    code: "human-required",
    label: "Human Required Today",
    description: "Cases requiring human intervention in last 24h",
    filterStageCode: "",
    urgency: "normal" as Urgency,
  },

];

export const HIGH_URGENCY_SURFACES = CG_ADMIN_SURFACES.filter(s => s.urgency === 'high');
