// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/connect-group-routes.ttl

import { WorkOrder } from '../types/routes';







export const CG_WORK_ORDERS: WorkOrder[] = [

  {
    code: "CreateGroupInterestWorkOrder",
    label: "Create Group Interest",
    mappedStageCode: "cg-interest-expressed",
    autonomicActionClass: "A1",
    requiresHumanApproval: false,
  },

  {
    code: "SendGroupInviteWorkOrder",
    label: "Send Group Invite",
    mappedStageCode: "cg-invite-sent",
    autonomicActionClass: "A2",
    requiresHumanApproval: false,
  },

  {
    code: "AcceptGroupInviteWorkOrder",
    label: "Accept Group Invite",
    mappedStageCode: "cg-invite-accepted",
    autonomicActionClass: "A1",
    requiresHumanApproval: false,
  },

  {
    code: "ReserveGroupSpotWorkOrder",
    label: "Reserve Group Spot",
    mappedStageCode: "cg-eligible-groups-found",
    autonomicActionClass: "A2",
    requiresHumanApproval: false,
  },

  {
    code: "RecordGroupAttendanceWorkOrder",
    label: "Record Group Attendance",
    mappedStageCode: "cg-first-meeting-attended",
    autonomicActionClass: "A1",
    requiresHumanApproval: false,
  },

  {
    code: "CreateGroupFollowUpWorkOrder",
    label: "Create Group Follow-Up",
    mappedStageCode: "cg-followup-completed",
    autonomicActionClass: "A1",
    requiresHumanApproval: false,
  },

  {
    code: "CloseGroupJoinRouteWorkOrder",
    label: "Close Group Join Route",
    mappedStageCode: "cg-membership-active",
    autonomicActionClass: "A1",
    requiresHumanApproval: false,
  },

];

export type CGWorkOrderCode = "CreateGroupInterestWorkOrder" | "SendGroupInviteWorkOrder" | "AcceptGroupInviteWorkOrder" | "ReserveGroupSpotWorkOrder" | "RecordGroupAttendanceWorkOrder" | "CreateGroupFollowUpWorkOrder" | "CloseGroupJoinRouteWorkOrder";
