// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/care.ttl + extract-followup-rules.rq

import { FollowUpRule } from '../types/care';







export const FOLLOWUP_RULES: FollowUpRule[] = [

  {
    label: "Crisis Immediate Call",
    triggerCondition: "Crisis",
    followUpAction: "Call",
    daysAfter: 1,
    assignedRoles: "Pastoral Staff".split("|").filter(Boolean),
  },

  {
    label: "Bereavement Home Visit",
    triggerCondition: "Bereavement",
    followUpAction: "Home Visit",
    daysAfter: 3,
    assignedRoles: "Care Team Lead".split("|").filter(Boolean),
  },

  {
    label: "Food Need Text Confirmation",
    triggerCondition: "Food Need",
    followUpAction: "Text",
    daysAfter: 2,
    assignedRoles: "Pastoral Staff".split("|").filter(Boolean),
  },

  {
    label: "Prayer Encouragement Text",
    triggerCondition: "Prayer",
    followUpAction: "Text",
    daysAfter: 7,
    assignedRoles: "Care Team Volunteer".split("|").filter(Boolean),
  },

  {
    label: "Hospital Pastoral Visit",
    triggerCondition: "Hospital",
    followUpAction: "Church Visit",
    daysAfter: 1,
    assignedRoles: "Care Team Lead".split("|").filter(Boolean),
  },

  {
    label: "Benevolence Email Follow-Through",
    triggerCondition: "Benevolence",
    followUpAction: "Email",
    daysAfter: 5,
    assignedRoles: "Care Team Volunteer".split("|").filter(Boolean),
  },

];
