// Generated by CodeManufactory — do not edit
// Source: ontology/zoela/resource.ttl + extract-resource-matching-rules.rq

import { ResourceMatch } from '../types/resources';







export const RESOURCE_MATCHES: ResourceMatch[] = [

  {
    label: "Dry Goods Food Box",
    type: "Food Resource",
    capacity: 50,
    eligibilityCriteria: "No minimum age. No consent required.",
    applicableRoutes: "Food Need Route".split("|").filter(Boolean),
  },

  {
    label: "Emergency Benevolence Fund",
    type: "Benevolence Fund",
    capacity: 5000,
    eligibilityCriteria: "Minimum age: 18. Requires signed consent.",
    applicableRoutes: "Community Outreach Route".split("|").filter(Boolean),
  },

  {
    label: "Care Volunteer Hours",
    type: "Volunteer Time Resource",
    capacity: 20,
    eligibilityCriteria: "No minimum age. Pastoral assignment required.",
    applicableRoutes: "Benevolence Route".split("|").filter(Boolean),
  },

];
